version: "2"

run:
  timeout: 5m
  tests: false

linters:
  default: 'none'
  enable:
    - errcheck
    - gosec
    - misspell
    - unconvert
    - unparam

  settings:
    errcheck:
      exclude-functions:
        - (*database/sql.DB).Close
        - (*database/sql.Rows).Close
        - (*database/sql.Tx).Rollback
        - (*database/sql.Stmt).Close
        - (*database/sql.Conn).Close
        - (*os.File).Close
        - os.RemoveAll
        - os.Remove
        - os.Setenv
        - os.Unsetenv
        - os.Chdir
        - os.MkdirAll
        - fmt.Sscanf
        - fmt.Fprintf
        - syscall.Flock
        - golang.org/x/term.Restore
        # WebSocket close/write — best-effort during cleanup or context cancellation
        - (*github.com/gorilla/websocket.Conn).Close
        - (*github.com/gorilla/websocket.Conn).WriteMessage
        # NATS connection drain during shutdown — best-effort cleanup
        - (*github.com/nats-io/nats.go.Conn).Drain
        # NATS subscription unsubscribe — best-effort cleanup
        - (*github.com/nats-io/nats.go.Subscription).Unsubscribe
        # Cobra flag setup — panics on invalid flag name, safe to ignore
        - (*github.com/spf13/cobra.Command).MarkFlagRequired
        # Process wait in deferred cleanup after cancel
        - (*os/exec.Cmd).Wait
        # Redis client close on failed ping (error path cleanup)
        - (*github.com/redis/go-redis/v9.Client).Close
        # RPC client close — non-critical cleanup after request
        - (*github.com/steveyegge/beads/internal/rpc.Client).Close
        # Storage interface close — deferred cleanup
        - (github.com/steveyegge/beads/internal/storage.Storage).Close
        # DoltStore Rows close — deferred cleanup (custom sql.Rows wrapper)
        - (*github.com/steveyegge/beads/internal/storage/dolt.Rows).Close
        # Net listener close — best-effort cleanup (e.g., findFreePort)
        - (net.Listener).Close
        # Eventbus dispatch — fire-and-forget event publishing
        - (*github.com/steveyegge/beads/internal/eventbus.Bus).Dispatch
        # Slackbot notifications — best-effort, errors logged internally
        - (*github.com/steveyegge/beads/internal/slackbot.Bot).NotifyResolution
        - (*github.com/steveyegge/beads/internal/slackbot.Bot).NotifyEscalation
        - (*github.com/steveyegge/beads/internal/slackbot.Bot).NotifyNewDecision
    misspell:
      locale: US

  exclusions:
    rules:
      # G304: File inclusion via variable in tests is safe (test data)
      - path: '_test\.go'
        linters:
          - gosec
        text: "G304"
      # G306: File permissions 0644 in tests are acceptable (test fixtures)
      - path: '_test\.go'
        linters:
          - gosec
        text: "G306"
      # G304: Safe file reads from known JSONL and error paths
      - path: 'cmd/bd/autoflush\.go|cmd/bd/daemon_autostart\.go|cmd/bd/doctor/fix/sync_branch\.go|cmd/bd/doctor/git\.go|cmd/bd/rename_prefix\.go|cmd/bd/sync_merge\.go|internal/beads/beads\.go|internal/daemon/discovery\.go|internal/daemonrunner/sync\.go|internal/syncbranch/worktree\.go'
        linters:
          - gosec
        text: "G304"
      # G302/G306: Directory/file permissions 0700/0750 are acceptable
      - linters:
          - gosec
        text: "G302.*0700|G301.*0750"
      # G302/G306: JSONL files and error logs need 0644 for debugging/sharing
      - path: 'cmd/bd/autoflush\.go|cmd/bd/daemon\.go|cmd/bd/daemon_sync_branch\.go|cmd/bd/resolve_conflicts\.go|cmd/bd/setup\.go|cmd/bd/systemd\.go|internal/daemon/registry\.go|internal/daemonrunner/daemon\.go|internal/git/worktree\.go'
        linters:
          - gosec
        text: "G306"
      # G306: Git hooks must be executable (0700)
      - path: 'cmd/bd/init\.go'
        linters:
          - gosec
        text: "G306.*0700"
      # G204: Safe subprocess launches with validated arguments
      - path: 'cmd/bd/agent_attach\.go|cmd/bd/daemon_autostart\.go|cmd/bd/daemon_guard\.go|cmd/bd/daemon_sync_branch\.go|cmd/bd/doctor\.go|cmd/bd/doctor/fix/sync_branch\.go|cmd/bd/gate\.go|cmd/bd/gate_discover\.go|cmd/bd/jira\.go|cmd/bd/migrate_sync\.go|cmd/bd/show\.go|cmd/bd/sync\.go|internal/git/worktree\.go|internal/syncbranch/worktree\.go|internal/tui/decision/model\.go'
        linters:
          - gosec
        text: 'G204'
      # G104: Deferred file closes - errors are non-critical
      - path: 'cmd/bd/show\.go'
        linters:
          - gosec
        text: "G104.*Close"
      # G115: Safe integer conversions in backoff calculations
      - path: 'cmd/bd/daemon_autostart\.go'
        linters:
          - gosec
        text: "G115"
      # G201: SQL with fmt.Sprintf using placeholders (IN clause expansion)
      - path: 'internal/storage/sqlite/(dependencies|batch_ops)\.go'
        linters:
          - gosec
        text: "G201"
      # errcheck: Ignore unchecked errors in test files for common cleanup patterns
      - path: '_test\.go'
        linters:
          - errcheck
        text: "Error return value of .*(Close|Rollback|RemoveAll|Setenv|Unsetenv|Chdir|MkdirAll|Remove|Write|SetReadDeadline|SetDeadline|Start|Stop).* is not checked"

      # errcheck: WebSocket conn.Close — best-effort cleanup in agent attach
      - path: 'cmd/bd/agent_attach\.go'
        linters:
          - errcheck
        text: "conn\\.Close"
      # errcheck: Redis client.Close on failed ping — best-effort cleanup
      - path: 'internal/daemon/redis_wisp_store\.go'
        linters:
          - errcheck
        text: "client\\.Close"
      # errcheck: Stdout/Stderr writes are best-effort in attach flows
      - path: 'internal/coop/attach\.go'
        linters:
          - errcheck
        text: "opts\\.Stdout\\.Write|opts\\.Stderr|fmt\\.Fprintf"
      # errcheck: HTTP response body Close in deferred cleanup
      - path: 'internal/coop/client\.go|internal/rpc/http_client\.go|internal/rpc/http_client_sse\.go|internal/eventbus/handlers_mail\.go|internal/slackbot/cred_watcher\.go'
        linters:
          - errcheck
        text: "resp\\.Body\\.Close"
      # errcheck: HTTP ResponseWriter.Write — cannot handle errors mid-response
      - path: 'internal/rpc/http_server\.go|internal/slackbot/health\.go'
        linters:
          - errcheck
        text: "w\\.Write"

      # unparam: Placeholder functions that may return errors in future implementation
      - path: 'cmd/bd/jira\.go'
        linters:
          - unparam
        text: 'reimportConflicts|resolveConflictsByTimestamp'
      # unparam: ctx params kept for interface consistency and future use
      - path: 'cmd/bd/agent_attach\.go'
        linters:
          - unparam
        text: 'resolveAgentPodInfo.*ctx'
      - path: 'cmd/bd/decision_stop_check\.go'
        linters:
          - unparam
        text: 'ctx.*is unused|checkDecisionResponse.*result'
      - path: 'cmd/bd/routed\.go'
        linters:
          - unparam
        text: 'forEachRoutedID.*(ctx|localStore)'
      - path: 'cmd/bd/skill\.go'
        linters:
          - unparam
        text: 'ensureAgentBeadExists.*ctx'
      - path: 'cmd/bd/sync_export\.go'
        linters:
          - unparam
        text: 'exportToJSONLDeferred.*ctx'
      - path: 'internal/rpc/server_mol\.go'
        linters:
          - unparam
        text: 'ctx.*is unused|cookFormula.*ctx'
      - path: 'internal/rpc/server_write_ops\.go'
        linters:
          - unparam
        text: 'cookFormulaFull.*(ctx|conditionVars)'
      - path: 'internal/slackbot/nats\.go'
        linters:
          - unparam
        text: 'connect.*ctx'
      # unparam: args/issue params kept for cobra command signature consistency
      - path: 'cmd/bd/advice_list\.go'
        linters:
          - unparam
        text: 'matchesSubscriptions.*issue'
      - path: 'cmd/bd/cook\.go'
        linters:
          - unparam
        text: 'outputCookEphemeral.*vars'
      - path: 'cmd/bd/show\.go'
        linters:
          - unparam
        text: 'showIssueRefs.*args|showIssueChildren.*args'
      # unparam: Parameters kept for API stability — used by callers or planned features
      - path: 'internal/rpc/server_core\.go'
        linters:
          - unparam
        text: 'emitMutation.*assignee'
      - path: 'internal/rpc/server_mol\.go'
        linters:
          - unparam
        text: 'handleMolBondDryRun.*actor|looksLikeFormulaName.*result|spawnSubgraph.*(parentID|childRef)|burnMolecules'
      - path: 'internal/slackbot/bot\.go'
        linters:
          - unparam
        text: 'ensureBreakOutChannelExists.*agent|truncateForSlack.*maxLen'
      - path: 'internal/storage/dolt/watchdog\.go'
        linters:
          - unparam
        text: 'execContext.*result'

      # gosec G602: Slice bounds checked in surrounding logic
      - path: 'cmd/bd/decision_show\.go'
        linters:
          - gosec
        text: 'G602'
      # gosec G304: File inclusion via variable — paths from trusted config/CLI args
      - path: 'cmd/bd/route\.go|cmd/bd/runbook\.go|internal/gate/builtin_userprompt\.go|internal/slackbot/router\.go'
        linters:
          - gosec
        text: 'G304'
      # gosec G204: Subprocess launched with variable — commands from trusted config
      - path: 'cmd/bd/systemd\.go|internal/eventbus/external_handler\.go|internal/eventbus/handlers\.go|internal/gate/builtin_bridge\.go'
        linters:
          - gosec
        text: 'G204'
      # gosec G104: Errors unhandled in spike/test utility code and best-effort cleanup
      - path: 'cmd/nats-spike/main\.go|internal/coop/attach\.go|internal/coop/watcher\.go|internal/rpc/http_server\.go|internal/storage/dolt/watchdog\.go|internal/validation/semantic_id\.go'
        linters:
          - gosec
        text: 'G104'
      # gosec G306: WriteFile 0644 permissions are appropriate for config/temp files
      - path: 'cmd/bd/route\.go|cmd/bd/runbook\.go|internal/gate/builtin_userprompt\.go|internal/inject/queue\.go|internal/slackbot/preferences\.go|internal/slackbot/router\.go|internal/slackbot/state\.go'
        linters:
          - gosec
        text: 'G30[26]'
      # gosec G402: TLS InsecureSkipVerify — intentional for local daemon connections
      - path: 'internal/rpc/http_client\.go|internal/rpc/http_client_sse\.go'
        linters:
          - gosec
        text: 'G402'
      # gosec G112: ReadHeaderTimeout — internal health server, not public-facing
      - path: 'internal/slackbot/health\.go'
        linters:
          - gosec
        text: 'G112'

      # misspell: "cancelled" is intentional - matching GitHub API response values
      - path: 'cmd/bd/gate\.go'
        linters:
          - misspell
        text: 'cancelled'
      # misspell: "cancelled" in SQL LIKE clause — must match stored data values
      - path: 'internal/storage/dolt/blocked_cache\.go'
        linters:
          - misspell
        text: 'cancelled'

issues:
  uniq-by-line: true
