version: "2"
run:
  tests: false
linters:
  enable:
    - errcheck
    - gosec
    - misspell
    - unconvert
    - unparam
  disable:
    - dupl
    - goconst
    - revive
  settings:
    dupl:
      threshold: 100
    errcheck:
      check-type-assertions: false
      check-blank: false
      exclude-functions:
        - (*database/sql.DB).Close
        - (*database/sql.Rows).Close
        - (*database/sql.Tx).Rollback
        - (*database/sql.Stmt).Close
        - (*database/sql.Conn).Close
        - (*os.File).Close
        - (os).RemoveAll
        - (os).Remove
        - (os).Setenv
        - (os).Unsetenv
        - (os).Chdir
        - (os).MkdirAll
    goconst:
      min-len: 3
      min-occurrences: 3
    gocyclo:
      min-complexity: 15
    misspell:
      locale: US
    revive:
      rules:
        - name: var-naming
        - name: exported
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      # Allow empty branches in conditionals - often used for clarity
      - linters:
          - staticcheck
        text: "SA9003:"
      # Allow error strings with punctuation/newlines for user-facing messages
      - linters:
          - staticcheck
        text: "ST1005:"
      # Allow unused parameters - often required by interface implementations
      - linters:
          - unparam
        text: "is unused"
      # Allow unused functions - may be used in future or by other packages
      - linters:
          - unused
        text: "is unused"
      - linters:
          - gosec
        path: _test\.go
        text: G304.*file inclusion via variable
      - linters:
          - gosec
        text: G302.*0700|G301.*0750
      - linters:
          - gosec
        path: cmd/bd/init\.go
        text: G306.*0700
      - linters:
          - gosec
        text: G204.*git.*show|G204.*daemon
      - linters:
          - errcheck
        path: _test\.go
        text: Error return value of .*(Close|Rollback|RemoveAll|Setenv|Unsetenv|Chdir|MkdirAll|Remove|Write|SetReadDeadline|SetDeadline|Start|Stop).* is not checked
      - path: (.+)\.go$
        text: 'var-naming: avoid meaningless package names'
      - path: (.+)\.go$
        text: exported.*SQLiteStorage.*stutters
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
