# GoReleaser config for groblegark/beads fork releases.
# Simplified: linux + darwin only, no Windows signing, no cross-compile deps.

version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: bd-linux-amd64
    main: ./cmd/bd
    binary: bd
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
      - -X main.Build={{.ShortCommit}}
      - -X main.Commit={{.Commit}}

  - id: bd-linux-arm64
    main: ./cmd/bd
    binary: bd
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - arm64
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
      - -X main.Build={{.ShortCommit}}
      - -X main.Commit={{.Commit}}

  - id: bd-darwin-amd64
    main: ./cmd/bd
    binary: bd
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - amd64
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
      - -X main.Build={{.ShortCommit}}
      - -X main.Commit={{.Commit}}

  - id: bd-darwin-arm64
    main: ./cmd/bd
    binary: bd
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - arm64
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
      - -X main.Build={{.ShortCommit}}
      - -X main.Commit={{.Commit}}

archives:
  - id: bd-archive
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "Merge pull request"
      - "Merge branch"

release:
  # Omitting github owner/name lets goreleaser use the current repo
  draft: false
  prerelease: auto
  name_template: "v{{.Version}}"

announce:
  skip: true
