# GoReleaser config for groblegark/beads fork releases.
# CGO required for dolthub deps (gozstd, go-mysql-server regex).
# Cross-compilation needs platform-specific C toolchains.

version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: bd-linux-amd64
    main: ./cmd/bd
    binary: bd
    env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
      - -X main.Build={{.ShortCommit}}
      - -X main.Commit={{.Commit}}

  - id: bd-linux-arm64
    main: ./cmd/bd
    binary: bd
    env:
      - CGO_ENABLED=1
      - CC=aarch64-linux-gnu-gcc
      - CXX=aarch64-linux-gnu-g++
    goos:
      - linux
    goarch:
      - arm64
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
      - -X main.Build={{.ShortCommit}}
      - -X main.Commit={{.Commit}}

archives:
  - id: bd-archive
    formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "Merge pull request"
      - "Merge branch"

release:
  draft: false
  prerelease: auto
  name_template: "v{{.Version}}"

announce:
  skip: true
