// Code generated by bddgen. DO NOT EDIT.

package rpc

import (
	"context"
	"errors"
	"fmt"
	"github.com/steveyegge/beads/internal/storage"
	"github.com/steveyegge/beads/internal/types"
	"net/rpc"
	"time"
)

// daemonClient implements storage.Storage over net/rpc.
type daemonClient struct {
	client *rpc.Client
}

// Close closes the underlying RPC connection.
func (c *daemonClient) Close() error {
	return c.client.Close()
}

// RunInTransaction is not supported over the daemon RPC boundary.
func (c *daemonClient) RunInTransaction(ctx context.Context, commitMsg string, fn func(storage.Transaction) error) error {
	return fmt.Errorf("RunInTransaction: not supported over daemon RPC")
}

func decodeRPCError(r *RPCError) error {
	if r == nil {
		return nil
	}
	switch r.Kind {
	case "ErrAlreadyClaimed":
		return fmt.Errorf("%s: %w", r.Msg, storage.ErrAlreadyClaimed)
	case "ErrNotClaimable":
		return fmt.Errorf("%s: %w", r.Msg, storage.ErrNotClaimable)
	case "ErrNotFound":
		return fmt.Errorf("%s: %w", r.Msg, storage.ErrNotFound)
	case "ErrNotInitialized":
		return fmt.Errorf("%s: %w", r.Msg, storage.ErrNotInitialized)
	case "ErrPrefixMismatch":
		return fmt.Errorf("%s: %w", r.Msg, storage.ErrPrefixMismatch)
	case "ErrTooManyIterators":
		return fmt.Errorf("%s: %w", r.Msg, storage.ErrTooManyIterators)
	case "ErrIterSessionNotFound":
		return fmt.Errorf("%s: %w", r.Msg, storage.ErrIterSessionNotFound)
	default:
		return errors.New(r.Msg)
	}
}

func (c *daemonClient) CreateIssue(ctx context.Context, issue *types.Issue, actor string) error {
	args := &CreateIssueArgs{Issue: issue, Actor: actor}
	var reply CreateIssueReply
	if err := c.client.Call("daemonServer.CreateIssue", args, &reply); err != nil {
		return err
	}
	return decodeRPCError(reply.RPCError)
}

func (c *daemonClient) CreateIssues(ctx context.Context, issues []*types.Issue, actor string) error {
	args := &CreateIssuesArgs{Issues: issues, Actor: actor}
	var reply CreateIssuesReply
	if err := c.client.Call("daemonServer.CreateIssues", args, &reply); err != nil {
		return err
	}
	return decodeRPCError(reply.RPCError)
}

func (c *daemonClient) GetIssue(ctx context.Context, id string) (*types.Issue, error) {
	args := &GetIssueArgs{Id: id}
	var reply GetIssueReply
	if err := c.client.Call("daemonServer.GetIssue", args, &reply); err != nil {
		return nil, err
	}
	return reply.Issue, decodeRPCError(reply.RPCError)
}

func (c *daemonClient) GetIssueByExternalRef(ctx context.Context, externalRef string) (*types.Issue, error) {
	args := &GetIssueByExternalRefArgs{ExternalRef: externalRef}
	var reply GetIssueByExternalRefReply
	if err := c.client.Call("daemonServer.GetIssueByExternalRef", args, &reply); err != nil {
		return nil, err
	}
	return reply.Issue, decodeRPCError(reply.RPCError)
}

func (c *daemonClient) GetIssuesByIDs(ctx context.Context, ids []string) ([]*types.Issue, error) {
	args := &GetIssuesByIDsArgs{Ids: ids}
	var reply GetIssuesByIDsReply
	if err := c.client.Call("daemonServer.GetIssuesByIDs", args, &reply); err != nil {
		return nil, err
	}
	return reply.Issues, decodeRPCError(reply.RPCError)
}

func (c *daemonClient) UpdateIssue(ctx context.Context, id string, updates map[string]interface{}, actor string) error {
	args := &UpdateIssueArgs{Id: id, Updates: updates, Actor: actor}
	var reply UpdateIssueReply
	if err := c.client.Call("daemonServer.UpdateIssue", args, &reply); err != nil {
		return err
	}
	return decodeRPCError(reply.RPCError)
}

func (c *daemonClient) ReopenIssue(ctx context.Context, id string, reason string, actor string) error {
	args := &ReopenIssueArgs{Id: id, Reason: reason, Actor: actor}
	var reply ReopenIssueReply
	if err := c.client.Call("daemonServer.ReopenIssue", args, &reply); err != nil {
		return err
	}
	return decodeRPCError(reply.RPCError)
}

func (c *daemonClient) UpdateIssueType(ctx context.Context, id string, issueType string, actor string) error {
	args := &UpdateIssueTypeArgs{Id: id, IssueType: issueType, Actor: actor}
	var reply UpdateIssueTypeReply
	if err := c.client.Call("daemonServer.UpdateIssueType", args, &reply); err != nil {
		return err
	}
	return decodeRPCError(reply.RPCError)
}

func (c *daemonClient) CloseIssue(ctx context.Context, id string, reason string, actor string, session string) error {
	args := &CloseIssueArgs{Id: id, Reason: reason, Actor: actor, Session: session}
	var reply CloseIssueReply
	if err := c.client.Call("daemonServer.CloseIssue", args, &reply); err != nil {
		return err
	}
	return decodeRPCError(reply.RPCError)
}

func (c *daemonClient) DeleteIssue(ctx context.Context, id string) error {
	args := &DeleteIssueArgs{Id: id}
	var reply DeleteIssueReply
	if err := c.client.Call("daemonServer.DeleteIssue", args, &reply); err != nil {
		return err
	}
	return decodeRPCError(reply.RPCError)
}

func (c *daemonClient) SearchIssues(ctx context.Context, query string, filter types.IssueFilter) ([]*types.Issue, error) {
	args := &SearchIssuesArgs{Query: query, Filter: filter}
	var reply SearchIssuesReply
	if err := c.client.Call("daemonServer.SearchIssues", args, &reply); err != nil {
		return nil, err
	}
	return reply.Issues, decodeRPCError(reply.RPCError)
}

func (c *daemonClient) AddDependency(ctx context.Context, dep *types.Dependency, actor string) error {
	args := &AddDependencyArgs{Dep: dep, Actor: actor}
	var reply AddDependencyReply
	if err := c.client.Call("daemonServer.AddDependency", args, &reply); err != nil {
		return err
	}
	return decodeRPCError(reply.RPCError)
}

func (c *daemonClient) RemoveDependency(ctx context.Context, issueID string, dependsOnID string, actor string) error {
	args := &RemoveDependencyArgs{IssueID: issueID, DependsOnID: dependsOnID, Actor: actor}
	var reply RemoveDependencyReply
	if err := c.client.Call("daemonServer.RemoveDependency", args, &reply); err != nil {
		return err
	}
	return decodeRPCError(reply.RPCError)
}

func (c *daemonClient) GetDependencies(ctx context.Context, issueID string) ([]*types.Issue, error) {
	args := &GetDependenciesArgs{IssueID: issueID}
	var reply GetDependenciesReply
	if err := c.client.Call("daemonServer.GetDependencies", args, &reply); err != nil {
		return nil, err
	}
	return reply.Issues, decodeRPCError(reply.RPCError)
}

func (c *daemonClient) GetDependents(ctx context.Context, issueID string) ([]*types.Issue, error) {
	args := &GetDependentsArgs{IssueID: issueID}
	var reply GetDependentsReply
	if err := c.client.Call("daemonServer.GetDependents", args, &reply); err != nil {
		return nil, err
	}
	return reply.Issues, decodeRPCError(reply.RPCError)
}

func (c *daemonClient) GetDependenciesWithMetadata(ctx context.Context, issueID string) ([]*types.IssueWithDependencyMetadata, error) {
	args := &GetDependenciesWithMetadataArgs{IssueID: issueID}
	var reply GetDependenciesWithMetadataReply
	if err := c.client.Call("daemonServer.GetDependenciesWithMetadata", args, &reply); err != nil {
		return nil, err
	}
	return reply.IssueWithDependencyMetadatas, decodeRPCError(reply.RPCError)
}

func (c *daemonClient) GetDependentsWithMetadata(ctx context.Context, issueID string) ([]*types.IssueWithDependencyMetadata, error) {
	args := &GetDependentsWithMetadataArgs{IssueID: issueID}
	var reply GetDependentsWithMetadataReply
	if err := c.client.Call("daemonServer.GetDependentsWithMetadata", args, &reply); err != nil {
		return nil, err
	}
	return reply.IssueWithDependencyMetadatas, decodeRPCError(reply.RPCError)
}

func (c *daemonClient) GetDependencyTree(ctx context.Context, issueID string, maxDepth int, showAllPaths bool, reverse bool) ([]*types.TreeNode, error) {
	args := &GetDependencyTreeArgs{IssueID: issueID, MaxDepth: maxDepth, ShowAllPaths: showAllPaths, Reverse: reverse}
	var reply GetDependencyTreeReply
	if err := c.client.Call("daemonServer.GetDependencyTree", args, &reply); err != nil {
		return nil, err
	}
	return reply.TreeNodes, decodeRPCError(reply.RPCError)
}

func (c *daemonClient) AddLabel(ctx context.Context, issueID string, label string, actor string) error {
	args := &AddLabelArgs{IssueID: issueID, Label: label, Actor: actor}
	var reply AddLabelReply
	if err := c.client.Call("daemonServer.AddLabel", args, &reply); err != nil {
		return err
	}
	return decodeRPCError(reply.RPCError)
}

func (c *daemonClient) RemoveLabel(ctx context.Context, issueID string, label string, actor string) error {
	args := &RemoveLabelArgs{IssueID: issueID, Label: label, Actor: actor}
	var reply RemoveLabelReply
	if err := c.client.Call("daemonServer.RemoveLabel", args, &reply); err != nil {
		return err
	}
	return decodeRPCError(reply.RPCError)
}

func (c *daemonClient) GetLabels(ctx context.Context, issueID string) ([]string, error) {
	args := &GetLabelsArgs{IssueID: issueID}
	var reply GetLabelsReply
	if err := c.client.Call("daemonServer.GetLabels", args, &reply); err != nil {
		return nil, err
	}
	return reply.Strings, decodeRPCError(reply.RPCError)
}

func (c *daemonClient) GetIssuesByLabel(ctx context.Context, label string) ([]*types.Issue, error) {
	args := &GetIssuesByLabelArgs{Label: label}
	var reply GetIssuesByLabelReply
	if err := c.client.Call("daemonServer.GetIssuesByLabel", args, &reply); err != nil {
		return nil, err
	}
	return reply.Issues, decodeRPCError(reply.RPCError)
}

func (c *daemonClient) GetReadyWork(ctx context.Context, filter types.WorkFilter) ([]*types.Issue, error) {
	args := &GetReadyWorkArgs{Filter: filter}
	var reply GetReadyWorkReply
	if err := c.client.Call("daemonServer.GetReadyWork", args, &reply); err != nil {
		return nil, err
	}
	return reply.Issues, decodeRPCError(reply.RPCError)
}

func (c *daemonClient) GetBlockedIssues(ctx context.Context, filter types.WorkFilter) ([]*types.BlockedIssue, error) {
	args := &GetBlockedIssuesArgs{Filter: filter}
	var reply GetBlockedIssuesReply
	if err := c.client.Call("daemonServer.GetBlockedIssues", args, &reply); err != nil {
		return nil, err
	}
	return reply.BlockedIssues, decodeRPCError(reply.RPCError)
}

func (c *daemonClient) GetEpicsEligibleForClosure(ctx context.Context) ([]*types.EpicStatus, error) {
	args := &GetEpicsEligibleForClosureArgs{}
	var reply GetEpicsEligibleForClosureReply
	if err := c.client.Call("daemonServer.GetEpicsEligibleForClosure", args, &reply); err != nil {
		return nil, err
	}
	return reply.EpicStatuss, decodeRPCError(reply.RPCError)
}

func (c *daemonClient) ListWisps(ctx context.Context, filter types.WispFilter) ([]*types.Issue, error) {
	args := &ListWispsArgs{Filter: filter}
	var reply ListWispsReply
	if err := c.client.Call("daemonServer.ListWisps", args, &reply); err != nil {
		return nil, err
	}
	return reply.Issues, decodeRPCError(reply.RPCError)
}

func (c *daemonClient) AddIssueComment(ctx context.Context, issueID string, author string, text string) (*types.Comment, error) {
	args := &AddIssueCommentArgs{IssueID: issueID, Author: author, Text: text}
	var reply AddIssueCommentReply
	if err := c.client.Call("daemonServer.AddIssueComment", args, &reply); err != nil {
		return nil, err
	}
	return reply.Comment, decodeRPCError(reply.RPCError)
}

func (c *daemonClient) GetIssueComments(ctx context.Context, issueID string) ([]*types.Comment, error) {
	args := &GetIssueCommentsArgs{IssueID: issueID}
	var reply GetIssueCommentsReply
	if err := c.client.Call("daemonServer.GetIssueComments", args, &reply); err != nil {
		return nil, err
	}
	return reply.Comments, decodeRPCError(reply.RPCError)
}

func (c *daemonClient) GetEvents(ctx context.Context, issueID string, limit int) ([]*types.Event, error) {
	args := &GetEventsArgs{IssueID: issueID, Limit: limit}
	var reply GetEventsReply
	if err := c.client.Call("daemonServer.GetEvents", args, &reply); err != nil {
		return nil, err
	}
	return reply.Events, decodeRPCError(reply.RPCError)
}

func (c *daemonClient) GetAllEventsSince(ctx context.Context, since time.Time) ([]*types.Event, error) {
	args := &GetAllEventsSinceArgs{Since: since}
	var reply GetAllEventsSinceReply
	if err := c.client.Call("daemonServer.GetAllEventsSince", args, &reply); err != nil {
		return nil, err
	}
	return reply.Events, decodeRPCError(reply.RPCError)
}

func (c *daemonClient) GetStatistics(ctx context.Context) (*types.Statistics, error) {
	args := &GetStatisticsArgs{}
	var reply GetStatisticsReply
	if err := c.client.Call("daemonServer.GetStatistics", args, &reply); err != nil {
		return nil, err
	}
	return reply.Statistics, decodeRPCError(reply.RPCError)
}

func (c *daemonClient) SetConfig(ctx context.Context, key string, value string) error {
	args := &SetConfigArgs{Key: key, Value: value}
	var reply SetConfigReply
	if err := c.client.Call("daemonServer.SetConfig", args, &reply); err != nil {
		return err
	}
	return decodeRPCError(reply.RPCError)
}

func (c *daemonClient) GetConfig(ctx context.Context, key string) (string, error) {
	args := &GetConfigArgs{Key: key}
	var reply GetConfigReply
	if err := c.client.Call("daemonServer.GetConfig", args, &reply); err != nil {
		return "", err
	}
	return reply.Value, decodeRPCError(reply.RPCError)
}

func (c *daemonClient) GetAllConfig(ctx context.Context) (map[string]string, error) {
	args := &GetAllConfigArgs{}
	var reply GetAllConfigReply
	if err := c.client.Call("daemonServer.GetAllConfig", args, &reply); err != nil {
		return nil, err
	}
	return reply.Data, decodeRPCError(reply.RPCError)
}

func (c *daemonClient) SetLocalMetadata(ctx context.Context, key string, value string) error {
	args := &SetLocalMetadataArgs{Key: key, Value: value}
	var reply SetLocalMetadataReply
	if err := c.client.Call("daemonServer.SetLocalMetadata", args, &reply); err != nil {
		return err
	}
	return decodeRPCError(reply.RPCError)
}

func (c *daemonClient) GetLocalMetadata(ctx context.Context, key string) (string, error) {
	args := &GetLocalMetadataArgs{Key: key}
	var reply GetLocalMetadataReply
	if err := c.client.Call("daemonServer.GetLocalMetadata", args, &reply); err != nil {
		return "", err
	}
	return reply.Value, decodeRPCError(reply.RPCError)
}

func (c *daemonClient) MergeSlotCreate(ctx context.Context, actor string) (*types.Issue, error) {
	args := &MergeSlotCreateArgs{Actor: actor}
	var reply MergeSlotCreateReply
	if err := c.client.Call("daemonServer.MergeSlotCreate", args, &reply); err != nil {
		return nil, err
	}
	return reply.Issue, decodeRPCError(reply.RPCError)
}

func (c *daemonClient) MergeSlotCheck(ctx context.Context) (*storage.MergeSlotStatus, error) {
	args := &MergeSlotCheckArgs{}
	var reply MergeSlotCheckReply
	if err := c.client.Call("daemonServer.MergeSlotCheck", args, &reply); err != nil {
		return nil, err
	}
	return reply.MergeSlotStatus, decodeRPCError(reply.RPCError)
}

func (c *daemonClient) MergeSlotAcquire(ctx context.Context, holder string, actor string, wait bool) (*storage.MergeSlotResult, error) {
	args := &MergeSlotAcquireArgs{Holder: holder, Actor: actor, Wait: wait}
	var reply MergeSlotAcquireReply
	if err := c.client.Call("daemonServer.MergeSlotAcquire", args, &reply); err != nil {
		return nil, err
	}
	return reply.MergeSlotResult, decodeRPCError(reply.RPCError)
}

func (c *daemonClient) MergeSlotRelease(ctx context.Context, holder string, actor string) error {
	args := &MergeSlotReleaseArgs{Holder: holder, Actor: actor}
	var reply MergeSlotReleaseReply
	if err := c.client.Call("daemonServer.MergeSlotRelease", args, &reply); err != nil {
		return err
	}
	return decodeRPCError(reply.RPCError)
}

func (c *daemonClient) SlotSet(ctx context.Context, issueID string, key string, value string, actor string) error {
	args := &SlotSetArgs{IssueID: issueID, Key: key, Value: value, Actor: actor}
	var reply SlotSetReply
	if err := c.client.Call("daemonServer.SlotSet", args, &reply); err != nil {
		return err
	}
	return decodeRPCError(reply.RPCError)
}

func (c *daemonClient) SlotGet(ctx context.Context, issueID string, key string) (string, error) {
	args := &SlotGetArgs{IssueID: issueID, Key: key}
	var reply SlotGetReply
	if err := c.client.Call("daemonServer.SlotGet", args, &reply); err != nil {
		return "", err
	}
	return reply.Value, decodeRPCError(reply.RPCError)
}

func (c *daemonClient) SlotClear(ctx context.Context, issueID string, key string, actor string) error {
	args := &SlotClearArgs{IssueID: issueID, Key: key, Actor: actor}
	var reply SlotClearReply
	if err := c.client.Call("daemonServer.SlotClear", args, &reply); err != nil {
		return err
	}
	return decodeRPCError(reply.RPCError)
}

func (c *daemonClient) SearchIssuesWithCounts(_ context.Context, _ string, _ types.IssueFilter) ([]*types.IssueWithCounts, error) {
	return nil, fmt.Errorf("SearchIssuesWithCounts: not supported over daemon RPC")
}

func (c *daemonClient) GetReadyWorkWithCounts(_ context.Context, _ types.WorkFilter) ([]*types.IssueWithCounts, error) {
	return nil, fmt.Errorf("GetReadyWorkWithCounts: not supported over daemon RPC")
}

func (c *daemonClient) CountIssues(_ context.Context, _ string, _ types.IssueFilter) (int64, error) {
	return 0, fmt.Errorf("CountIssues: not supported over daemon RPC")
}

func (c *daemonClient) CountDependents(_ context.Context, _ string) (int64, error) {
	return 0, fmt.Errorf("CountDependents: not supported over daemon RPC")
}

func (c *daemonClient) CountDependencies(_ context.Context, _ string) (int64, error) {
	return 0, fmt.Errorf("CountDependencies: not supported over daemon RPC")
}

func (c *daemonClient) CountIssueComments(_ context.Context, _ string) (int64, error) {
	return 0, fmt.Errorf("CountIssueComments: not supported over daemon RPC")
}

func (c *daemonClient) CountEvents(_ context.Context, _ string, _ int) (int64, error) {
	return 0, fmt.Errorf("CountEvents: not supported over daemon RPC")
}

func (c *daemonClient) CountDependentsByStatus(_ context.Context, _ string, _ types.Status) (int64, error) {
	return 0, fmt.Errorf("CountDependentsByStatus: not supported over daemon RPC")
}

var _ storage.Storage = (*daemonClient)(nil)
