// Package rpc provides net/rpc client and server wrappers for storage.Storage.
// types.go, server.go, and client.go are generated by bddgen — do not edit them.
//
//go:generate go run github.com/steveyegge/beads/cmd/bddgen -storage ../storage.go -deps ../dependency_queries.go -out .
package rpc
