// Code generated by bddgen. DO NOT EDIT.

package rpc

import (
	"context"
	"crypto/rand"
	"encoding/hex"
	"github.com/steveyegge/beads/internal/storage"
	"github.com/steveyegge/beads/internal/types"
	"sync"
	"sync/atomic"
	"time"
)

const defaultIterBatchSize = 100

// newSessionID returns a random 16-byte hex string for iterator session IDs.
func newSessionID() string {
	var buf [16]byte
	if _, err := rand.Read(buf[:]); err != nil {
		panic("bddgen: newSessionID: " + err.Error())
	}
	return hex.EncodeToString(buf[:])
}

// IterIssuesStart opens a new iterator session for IterIssues.
func (s *daemonServer) IterIssuesStart(args *IterIssuesStartArgs, reply *IterStartReply) error {
	ctx, cancel := daemonCallContext(s.root)
	defer cancel()
	it, err := s.store.IterIssues(ctx, args.Query, args.Filter)
	if err != nil {
		reply.RPCError = encodeRPCError(err)
		return nil
	}
	sess := &issuesIterSession{iter: it}
	sess.Touch()
	sessionID := newSessionID()
	if err := s.iterMgr.openSession(sessionID, sess); err != nil {
		_ = it.Close()
		reply.RPCError = encodeRPCError(err)
		return nil
	}
	reply.SessionID = sessionID
	return nil
}

// IterIssuesNext fetches the next batch from a IterIssues session.
func (s *daemonServer) IterIssuesNext(args *IterNextArgs, reply *IterIssuesNextReply) error {
	raw := s.iterMgr.getSession(args.SessionID)
	if raw == nil {
		reply.RPCError = encodeRPCError(storage.ErrIterSessionNotFound)
		return nil
	}
	sess, ok := raw.(*issuesIterSession)
	if !ok {
		reply.RPCError = encodeRPCError(storage.ErrIterSessionNotFound)
		return nil
	}
	sess.mu.Lock()
	defer sess.mu.Unlock()
	sess.Touch()
	batchSize := args.BatchSize
	if batchSize <= 0 {
		batchSize = defaultIterBatchSize
	}
	const maxIterBatchSize = 10000
	if batchSize > maxIterBatchSize {
		batchSize = maxIterBatchSize
	}
	ctx := context.Background()
	for len(reply.Items) < batchSize {
		if !sess.iter.Next(ctx) {
			reply.Done = true
			if iterErr := sess.iter.Err(); iterErr != nil {
				reply.RPCError = encodeRPCError(iterErr)
			}
			s.iterMgr.closeSession(args.SessionID)
			break
		}
		v := *sess.iter.Value()
		reply.Items = append(reply.Items, &v)
	}
	s.iterMgr.rowsStreamedTotal.Add(int64(len(reply.Items)))
	return nil
}

// issuesIterSession is the server-side session for IterIssues.
type issuesIterSession struct {
	mu       sync.Mutex
	iter     storage.Iter[types.Issue]
	lastUsed atomic.Int64
}

func (s *issuesIterSession) TypeName() string      { return "issuesIterSession" }
func (s *issuesIterSession) Touch()                { s.lastUsed.Store(time.Now().UnixNano()) }
func (s *issuesIterSession) LastUsedAt() time.Time { return time.Unix(0, s.lastUsed.Load()) }
func (s *issuesIterSession) Close() error          { return s.iter.Close() }

// IterDependentsWithMetadataStart opens a new iterator session for IterDependentsWithMetadata.
func (s *daemonServer) IterDependentsWithMetadataStart(args *IterDependentsWithMetadataStartArgs, reply *IterStartReply) error {
	ctx, cancel := daemonCallContext(s.root)
	defer cancel()
	it, err := s.store.IterDependentsWithMetadata(ctx, args.IssueID)
	if err != nil {
		reply.RPCError = encodeRPCError(err)
		return nil
	}
	sess := &dependentsWithMetadataIterSession{iter: it}
	sess.Touch()
	sessionID := newSessionID()
	if err := s.iterMgr.openSession(sessionID, sess); err != nil {
		_ = it.Close()
		reply.RPCError = encodeRPCError(err)
		return nil
	}
	reply.SessionID = sessionID
	return nil
}

// IterDependentsWithMetadataNext fetches the next batch from a IterDependentsWithMetadata session.
func (s *daemonServer) IterDependentsWithMetadataNext(args *IterNextArgs, reply *IterDependentsWithMetadataNextReply) error {
	raw := s.iterMgr.getSession(args.SessionID)
	if raw == nil {
		reply.RPCError = encodeRPCError(storage.ErrIterSessionNotFound)
		return nil
	}
	sess, ok := raw.(*dependentsWithMetadataIterSession)
	if !ok {
		reply.RPCError = encodeRPCError(storage.ErrIterSessionNotFound)
		return nil
	}
	sess.mu.Lock()
	defer sess.mu.Unlock()
	sess.Touch()
	batchSize := args.BatchSize
	if batchSize <= 0 {
		batchSize = defaultIterBatchSize
	}
	const maxIterBatchSize = 10000
	if batchSize > maxIterBatchSize {
		batchSize = maxIterBatchSize
	}
	ctx := context.Background()
	for len(reply.Items) < batchSize {
		if !sess.iter.Next(ctx) {
			reply.Done = true
			if iterErr := sess.iter.Err(); iterErr != nil {
				reply.RPCError = encodeRPCError(iterErr)
			}
			s.iterMgr.closeSession(args.SessionID)
			break
		}
		v := *sess.iter.Value()
		reply.Items = append(reply.Items, &v)
	}
	s.iterMgr.rowsStreamedTotal.Add(int64(len(reply.Items)))
	return nil
}

// dependentsWithMetadataIterSession is the server-side session for IterDependentsWithMetadata.
type dependentsWithMetadataIterSession struct {
	mu       sync.Mutex
	iter     storage.Iter[types.IssueWithDependencyMetadata]
	lastUsed atomic.Int64
}

func (s *dependentsWithMetadataIterSession) TypeName() string {
	return "dependentsWithMetadataIterSession"
}
func (s *dependentsWithMetadataIterSession) Touch() { s.lastUsed.Store(time.Now().UnixNano()) }
func (s *dependentsWithMetadataIterSession) LastUsedAt() time.Time {
	return time.Unix(0, s.lastUsed.Load())
}
func (s *dependentsWithMetadataIterSession) Close() error { return s.iter.Close() }

// IterDependenciesWithMetadataStart opens a new iterator session for IterDependenciesWithMetadata.
func (s *daemonServer) IterDependenciesWithMetadataStart(args *IterDependenciesWithMetadataStartArgs, reply *IterStartReply) error {
	ctx, cancel := daemonCallContext(s.root)
	defer cancel()
	it, err := s.store.IterDependenciesWithMetadata(ctx, args.IssueID)
	if err != nil {
		reply.RPCError = encodeRPCError(err)
		return nil
	}
	sess := &dependenciesWithMetadataIterSession{iter: it}
	sess.Touch()
	sessionID := newSessionID()
	if err := s.iterMgr.openSession(sessionID, sess); err != nil {
		_ = it.Close()
		reply.RPCError = encodeRPCError(err)
		return nil
	}
	reply.SessionID = sessionID
	return nil
}

// IterDependenciesWithMetadataNext fetches the next batch from a IterDependenciesWithMetadata session.
func (s *daemonServer) IterDependenciesWithMetadataNext(args *IterNextArgs, reply *IterDependenciesWithMetadataNextReply) error {
	raw := s.iterMgr.getSession(args.SessionID)
	if raw == nil {
		reply.RPCError = encodeRPCError(storage.ErrIterSessionNotFound)
		return nil
	}
	sess, ok := raw.(*dependenciesWithMetadataIterSession)
	if !ok {
		reply.RPCError = encodeRPCError(storage.ErrIterSessionNotFound)
		return nil
	}
	sess.mu.Lock()
	defer sess.mu.Unlock()
	sess.Touch()
	batchSize := args.BatchSize
	if batchSize <= 0 {
		batchSize = defaultIterBatchSize
	}
	const maxIterBatchSize = 10000
	if batchSize > maxIterBatchSize {
		batchSize = maxIterBatchSize
	}
	ctx := context.Background()
	for len(reply.Items) < batchSize {
		if !sess.iter.Next(ctx) {
			reply.Done = true
			if iterErr := sess.iter.Err(); iterErr != nil {
				reply.RPCError = encodeRPCError(iterErr)
			}
			s.iterMgr.closeSession(args.SessionID)
			break
		}
		v := *sess.iter.Value()
		reply.Items = append(reply.Items, &v)
	}
	s.iterMgr.rowsStreamedTotal.Add(int64(len(reply.Items)))
	return nil
}

// dependenciesWithMetadataIterSession is the server-side session for IterDependenciesWithMetadata.
type dependenciesWithMetadataIterSession struct {
	mu       sync.Mutex
	iter     storage.Iter[types.IssueWithDependencyMetadata]
	lastUsed atomic.Int64
}

func (s *dependenciesWithMetadataIterSession) TypeName() string {
	return "dependenciesWithMetadataIterSession"
}
func (s *dependenciesWithMetadataIterSession) Touch() { s.lastUsed.Store(time.Now().UnixNano()) }
func (s *dependenciesWithMetadataIterSession) LastUsedAt() time.Time {
	return time.Unix(0, s.lastUsed.Load())
}
func (s *dependenciesWithMetadataIterSession) Close() error { return s.iter.Close() }

// IterIssueCommentsStart opens a new iterator session for IterIssueComments.
func (s *daemonServer) IterIssueCommentsStart(args *IterIssueCommentsStartArgs, reply *IterStartReply) error {
	ctx, cancel := daemonCallContext(s.root)
	defer cancel()
	it, err := s.store.IterIssueComments(ctx, args.IssueID)
	if err != nil {
		reply.RPCError = encodeRPCError(err)
		return nil
	}
	sess := &issueCommentsIterSession{iter: it}
	sess.Touch()
	sessionID := newSessionID()
	if err := s.iterMgr.openSession(sessionID, sess); err != nil {
		_ = it.Close()
		reply.RPCError = encodeRPCError(err)
		return nil
	}
	reply.SessionID = sessionID
	return nil
}

// IterIssueCommentsNext fetches the next batch from a IterIssueComments session.
func (s *daemonServer) IterIssueCommentsNext(args *IterNextArgs, reply *IterIssueCommentsNextReply) error {
	raw := s.iterMgr.getSession(args.SessionID)
	if raw == nil {
		reply.RPCError = encodeRPCError(storage.ErrIterSessionNotFound)
		return nil
	}
	sess, ok := raw.(*issueCommentsIterSession)
	if !ok {
		reply.RPCError = encodeRPCError(storage.ErrIterSessionNotFound)
		return nil
	}
	sess.mu.Lock()
	defer sess.mu.Unlock()
	sess.Touch()
	batchSize := args.BatchSize
	if batchSize <= 0 {
		batchSize = defaultIterBatchSize
	}
	const maxIterBatchSize = 10000
	if batchSize > maxIterBatchSize {
		batchSize = maxIterBatchSize
	}
	ctx := context.Background()
	for len(reply.Items) < batchSize {
		if !sess.iter.Next(ctx) {
			reply.Done = true
			if iterErr := sess.iter.Err(); iterErr != nil {
				reply.RPCError = encodeRPCError(iterErr)
			}
			s.iterMgr.closeSession(args.SessionID)
			break
		}
		v := *sess.iter.Value()
		reply.Items = append(reply.Items, &v)
	}
	s.iterMgr.rowsStreamedTotal.Add(int64(len(reply.Items)))
	return nil
}

// issueCommentsIterSession is the server-side session for IterIssueComments.
type issueCommentsIterSession struct {
	mu       sync.Mutex
	iter     storage.Iter[types.Comment]
	lastUsed atomic.Int64
}

func (s *issueCommentsIterSession) TypeName() string      { return "issueCommentsIterSession" }
func (s *issueCommentsIterSession) Touch()                { s.lastUsed.Store(time.Now().UnixNano()) }
func (s *issueCommentsIterSession) LastUsedAt() time.Time { return time.Unix(0, s.lastUsed.Load()) }
func (s *issueCommentsIterSession) Close() error          { return s.iter.Close() }

// IterEventsStart opens a new iterator session for IterEvents.
func (s *daemonServer) IterEventsStart(args *IterEventsStartArgs, reply *IterStartReply) error {
	ctx, cancel := daemonCallContext(s.root)
	defer cancel()
	it, err := s.store.IterEvents(ctx, args.IssueID, args.Limit)
	if err != nil {
		reply.RPCError = encodeRPCError(err)
		return nil
	}
	sess := &eventsIterSession{iter: it}
	sess.Touch()
	sessionID := newSessionID()
	if err := s.iterMgr.openSession(sessionID, sess); err != nil {
		_ = it.Close()
		reply.RPCError = encodeRPCError(err)
		return nil
	}
	reply.SessionID = sessionID
	return nil
}

// IterEventsNext fetches the next batch from a IterEvents session.
func (s *daemonServer) IterEventsNext(args *IterNextArgs, reply *IterEventsNextReply) error {
	raw := s.iterMgr.getSession(args.SessionID)
	if raw == nil {
		reply.RPCError = encodeRPCError(storage.ErrIterSessionNotFound)
		return nil
	}
	sess, ok := raw.(*eventsIterSession)
	if !ok {
		reply.RPCError = encodeRPCError(storage.ErrIterSessionNotFound)
		return nil
	}
	sess.mu.Lock()
	defer sess.mu.Unlock()
	sess.Touch()
	batchSize := args.BatchSize
	if batchSize <= 0 {
		batchSize = defaultIterBatchSize
	}
	const maxIterBatchSize = 10000
	if batchSize > maxIterBatchSize {
		batchSize = maxIterBatchSize
	}
	ctx := context.Background()
	for len(reply.Items) < batchSize {
		if !sess.iter.Next(ctx) {
			reply.Done = true
			if iterErr := sess.iter.Err(); iterErr != nil {
				reply.RPCError = encodeRPCError(iterErr)
			}
			s.iterMgr.closeSession(args.SessionID)
			break
		}
		v := *sess.iter.Value()
		reply.Items = append(reply.Items, &v)
	}
	s.iterMgr.rowsStreamedTotal.Add(int64(len(reply.Items)))
	return nil
}

// eventsIterSession is the server-side session for IterEvents.
type eventsIterSession struct {
	mu       sync.Mutex
	iter     storage.Iter[types.Event]
	lastUsed atomic.Int64
}

func (s *eventsIterSession) TypeName() string      { return "eventsIterSession" }
func (s *eventsIterSession) Touch()                { s.lastUsed.Store(time.Now().UnixNano()) }
func (s *eventsIterSession) LastUsedAt() time.Time { return time.Unix(0, s.lastUsed.Load()) }
func (s *eventsIterSession) Close() error          { return s.iter.Close() }

// IterAllEventsSinceStart opens a new iterator session for IterAllEventsSince.
func (s *daemonServer) IterAllEventsSinceStart(args *IterAllEventsSinceStartArgs, reply *IterStartReply) error {
	ctx, cancel := daemonCallContext(s.root)
	defer cancel()
	it, err := s.store.IterAllEventsSince(ctx, args.Since)
	if err != nil {
		reply.RPCError = encodeRPCError(err)
		return nil
	}
	sess := &allEventsSinceIterSession{iter: it}
	sess.Touch()
	sessionID := newSessionID()
	if err := s.iterMgr.openSession(sessionID, sess); err != nil {
		_ = it.Close()
		reply.RPCError = encodeRPCError(err)
		return nil
	}
	reply.SessionID = sessionID
	return nil
}

// IterAllEventsSinceNext fetches the next batch from a IterAllEventsSince session.
func (s *daemonServer) IterAllEventsSinceNext(args *IterNextArgs, reply *IterAllEventsSinceNextReply) error {
	raw := s.iterMgr.getSession(args.SessionID)
	if raw == nil {
		reply.RPCError = encodeRPCError(storage.ErrIterSessionNotFound)
		return nil
	}
	sess, ok := raw.(*allEventsSinceIterSession)
	if !ok {
		reply.RPCError = encodeRPCError(storage.ErrIterSessionNotFound)
		return nil
	}
	sess.mu.Lock()
	defer sess.mu.Unlock()
	sess.Touch()
	batchSize := args.BatchSize
	if batchSize <= 0 {
		batchSize = defaultIterBatchSize
	}
	const maxIterBatchSize = 10000
	if batchSize > maxIterBatchSize {
		batchSize = maxIterBatchSize
	}
	ctx := context.Background()
	for len(reply.Items) < batchSize {
		if !sess.iter.Next(ctx) {
			reply.Done = true
			if iterErr := sess.iter.Err(); iterErr != nil {
				reply.RPCError = encodeRPCError(iterErr)
			}
			s.iterMgr.closeSession(args.SessionID)
			break
		}
		v := *sess.iter.Value()
		reply.Items = append(reply.Items, &v)
	}
	s.iterMgr.rowsStreamedTotal.Add(int64(len(reply.Items)))
	return nil
}

// allEventsSinceIterSession is the server-side session for IterAllEventsSince.
type allEventsSinceIterSession struct {
	mu       sync.Mutex
	iter     storage.Iter[types.Event]
	lastUsed atomic.Int64
}

func (s *allEventsSinceIterSession) TypeName() string      { return "allEventsSinceIterSession" }
func (s *allEventsSinceIterSession) Touch()                { s.lastUsed.Store(time.Now().UnixNano()) }
func (s *allEventsSinceIterSession) LastUsedAt() time.Time { return time.Unix(0, s.lastUsed.Load()) }
func (s *allEventsSinceIterSession) Close() error          { return s.iter.Close() }

// IterReadyWorkStart opens a new iterator session for IterReadyWork.
func (s *daemonServer) IterReadyWorkStart(args *IterReadyWorkStartArgs, reply *IterStartReply) error {
	ctx, cancel := daemonCallContext(s.root)
	defer cancel()
	it, err := s.store.IterReadyWork(ctx, args.Filter)
	if err != nil {
		reply.RPCError = encodeRPCError(err)
		return nil
	}
	sess := &readyWorkIterSession{iter: it}
	sess.Touch()
	sessionID := newSessionID()
	if err := s.iterMgr.openSession(sessionID, sess); err != nil {
		_ = it.Close()
		reply.RPCError = encodeRPCError(err)
		return nil
	}
	reply.SessionID = sessionID
	return nil
}

// IterReadyWorkNext fetches the next batch from a IterReadyWork session.
func (s *daemonServer) IterReadyWorkNext(args *IterNextArgs, reply *IterReadyWorkNextReply) error {
	raw := s.iterMgr.getSession(args.SessionID)
	if raw == nil {
		reply.RPCError = encodeRPCError(storage.ErrIterSessionNotFound)
		return nil
	}
	sess, ok := raw.(*readyWorkIterSession)
	if !ok {
		reply.RPCError = encodeRPCError(storage.ErrIterSessionNotFound)
		return nil
	}
	sess.mu.Lock()
	defer sess.mu.Unlock()
	sess.Touch()
	batchSize := args.BatchSize
	if batchSize <= 0 {
		batchSize = defaultIterBatchSize
	}
	const maxIterBatchSize = 10000
	if batchSize > maxIterBatchSize {
		batchSize = maxIterBatchSize
	}
	ctx := context.Background()
	for len(reply.Items) < batchSize {
		if !sess.iter.Next(ctx) {
			reply.Done = true
			if iterErr := sess.iter.Err(); iterErr != nil {
				reply.RPCError = encodeRPCError(iterErr)
			}
			s.iterMgr.closeSession(args.SessionID)
			break
		}
		v := *sess.iter.Value()
		reply.Items = append(reply.Items, &v)
	}
	s.iterMgr.rowsStreamedTotal.Add(int64(len(reply.Items)))
	return nil
}

// readyWorkIterSession is the server-side session for IterReadyWork.
type readyWorkIterSession struct {
	mu       sync.Mutex
	iter     storage.Iter[types.Issue]
	lastUsed atomic.Int64
}

func (s *readyWorkIterSession) TypeName() string      { return "readyWorkIterSession" }
func (s *readyWorkIterSession) Touch()                { s.lastUsed.Store(time.Now().UnixNano()) }
func (s *readyWorkIterSession) LastUsedAt() time.Time { return time.Unix(0, s.lastUsed.Load()) }
func (s *readyWorkIterSession) Close() error          { return s.iter.Close() }

// IterBlockedIssuesStart opens a new iterator session for IterBlockedIssues.
func (s *daemonServer) IterBlockedIssuesStart(args *IterBlockedIssuesStartArgs, reply *IterStartReply) error {
	ctx, cancel := daemonCallContext(s.root)
	defer cancel()
	it, err := s.store.IterBlockedIssues(ctx, args.Filter)
	if err != nil {
		reply.RPCError = encodeRPCError(err)
		return nil
	}
	sess := &blockedIssuesIterSession{iter: it}
	sess.Touch()
	sessionID := newSessionID()
	if err := s.iterMgr.openSession(sessionID, sess); err != nil {
		_ = it.Close()
		reply.RPCError = encodeRPCError(err)
		return nil
	}
	reply.SessionID = sessionID
	return nil
}

// IterBlockedIssuesNext fetches the next batch from a IterBlockedIssues session.
func (s *daemonServer) IterBlockedIssuesNext(args *IterNextArgs, reply *IterBlockedIssuesNextReply) error {
	raw := s.iterMgr.getSession(args.SessionID)
	if raw == nil {
		reply.RPCError = encodeRPCError(storage.ErrIterSessionNotFound)
		return nil
	}
	sess, ok := raw.(*blockedIssuesIterSession)
	if !ok {
		reply.RPCError = encodeRPCError(storage.ErrIterSessionNotFound)
		return nil
	}
	sess.mu.Lock()
	defer sess.mu.Unlock()
	sess.Touch()
	batchSize := args.BatchSize
	if batchSize <= 0 {
		batchSize = defaultIterBatchSize
	}
	const maxIterBatchSize = 10000
	if batchSize > maxIterBatchSize {
		batchSize = maxIterBatchSize
	}
	ctx := context.Background()
	for len(reply.Items) < batchSize {
		if !sess.iter.Next(ctx) {
			reply.Done = true
			if iterErr := sess.iter.Err(); iterErr != nil {
				reply.RPCError = encodeRPCError(iterErr)
			}
			s.iterMgr.closeSession(args.SessionID)
			break
		}
		v := *sess.iter.Value()
		reply.Items = append(reply.Items, &v)
	}
	s.iterMgr.rowsStreamedTotal.Add(int64(len(reply.Items)))
	return nil
}

// blockedIssuesIterSession is the server-side session for IterBlockedIssues.
type blockedIssuesIterSession struct {
	mu       sync.Mutex
	iter     storage.Iter[types.BlockedIssue]
	lastUsed atomic.Int64
}

func (s *blockedIssuesIterSession) TypeName() string      { return "blockedIssuesIterSession" }
func (s *blockedIssuesIterSession) Touch()                { s.lastUsed.Store(time.Now().UnixNano()) }
func (s *blockedIssuesIterSession) LastUsedAt() time.Time { return time.Unix(0, s.lastUsed.Load()) }
func (s *blockedIssuesIterSession) Close() error          { return s.iter.Close() }

// IterWispsStart opens a new iterator session for IterWisps.
func (s *daemonServer) IterWispsStart(args *IterWispsStartArgs, reply *IterStartReply) error {
	ctx, cancel := daemonCallContext(s.root)
	defer cancel()
	it, err := s.store.IterWisps(ctx, args.Filter)
	if err != nil {
		reply.RPCError = encodeRPCError(err)
		return nil
	}
	sess := &wispsIterSession{iter: it}
	sess.Touch()
	sessionID := newSessionID()
	if err := s.iterMgr.openSession(sessionID, sess); err != nil {
		_ = it.Close()
		reply.RPCError = encodeRPCError(err)
		return nil
	}
	reply.SessionID = sessionID
	return nil
}

// IterWispsNext fetches the next batch from a IterWisps session.
func (s *daemonServer) IterWispsNext(args *IterNextArgs, reply *IterWispsNextReply) error {
	raw := s.iterMgr.getSession(args.SessionID)
	if raw == nil {
		reply.RPCError = encodeRPCError(storage.ErrIterSessionNotFound)
		return nil
	}
	sess, ok := raw.(*wispsIterSession)
	if !ok {
		reply.RPCError = encodeRPCError(storage.ErrIterSessionNotFound)
		return nil
	}
	sess.mu.Lock()
	defer sess.mu.Unlock()
	sess.Touch()
	batchSize := args.BatchSize
	if batchSize <= 0 {
		batchSize = defaultIterBatchSize
	}
	const maxIterBatchSize = 10000
	if batchSize > maxIterBatchSize {
		batchSize = maxIterBatchSize
	}
	ctx := context.Background()
	for len(reply.Items) < batchSize {
		if !sess.iter.Next(ctx) {
			reply.Done = true
			if iterErr := sess.iter.Err(); iterErr != nil {
				reply.RPCError = encodeRPCError(iterErr)
			}
			s.iterMgr.closeSession(args.SessionID)
			break
		}
		v := *sess.iter.Value()
		reply.Items = append(reply.Items, &v)
	}
	s.iterMgr.rowsStreamedTotal.Add(int64(len(reply.Items)))
	return nil
}

// wispsIterSession is the server-side session for IterWisps.
type wispsIterSession struct {
	mu       sync.Mutex
	iter     storage.Iter[types.Issue]
	lastUsed atomic.Int64
}

func (s *wispsIterSession) TypeName() string      { return "wispsIterSession" }
func (s *wispsIterSession) Touch()                { s.lastUsed.Store(time.Now().UnixNano()) }
func (s *wispsIterSession) LastUsedAt() time.Time { return time.Unix(0, s.lastUsed.Load()) }
func (s *wispsIterSession) Close() error          { return s.iter.Close() }

// IterAllDependencyRecordsStart opens a new iterator session for IterAllDependencyRecords.
func (s *daemonServer) IterAllDependencyRecordsStart(args *IterAllDependencyRecordsStartArgs, reply *IterStartReply) error {
	ctx, cancel := daemonCallContext(s.root)
	defer cancel()
	store_IterAllDependencyRecords, ok := s.store.(storage.DependencyQueryStore)
	if !ok {
		reply.RPCError = &RPCError{Kind: "", Msg: "store does not implement storage.DependencyQueryStore"}
		return nil
	}
	it, err := store_IterAllDependencyRecords.IterAllDependencyRecords(ctx)
	if err != nil {
		reply.RPCError = encodeRPCError(err)
		return nil
	}
	sess := &allDependencyRecordsIterSession{iter: it}
	sess.Touch()
	sessionID := newSessionID()
	if err := s.iterMgr.openSession(sessionID, sess); err != nil {
		_ = it.Close()
		reply.RPCError = encodeRPCError(err)
		return nil
	}
	reply.SessionID = sessionID
	return nil
}

// IterAllDependencyRecordsNext fetches the next batch from a IterAllDependencyRecords session.
func (s *daemonServer) IterAllDependencyRecordsNext(args *IterNextArgs, reply *IterAllDependencyRecordsNextReply) error {
	raw := s.iterMgr.getSession(args.SessionID)
	if raw == nil {
		reply.RPCError = encodeRPCError(storage.ErrIterSessionNotFound)
		return nil
	}
	sess, ok := raw.(*allDependencyRecordsIterSession)
	if !ok {
		reply.RPCError = encodeRPCError(storage.ErrIterSessionNotFound)
		return nil
	}
	sess.mu.Lock()
	defer sess.mu.Unlock()
	sess.Touch()
	batchSize := args.BatchSize
	if batchSize <= 0 {
		batchSize = defaultIterBatchSize
	}
	const maxIterBatchSize = 10000
	if batchSize > maxIterBatchSize {
		batchSize = maxIterBatchSize
	}
	ctx := context.Background()
	for len(reply.Items) < batchSize {
		if !sess.iter.Next(ctx) {
			reply.Done = true
			if iterErr := sess.iter.Err(); iterErr != nil {
				reply.RPCError = encodeRPCError(iterErr)
			}
			s.iterMgr.closeSession(args.SessionID)
			break
		}
		v := *sess.iter.Value()
		reply.Items = append(reply.Items, &v)
	}
	s.iterMgr.rowsStreamedTotal.Add(int64(len(reply.Items)))
	return nil
}

// allDependencyRecordsIterSession is the server-side session for IterAllDependencyRecords.
type allDependencyRecordsIterSession struct {
	mu       sync.Mutex
	iter     storage.Iter[types.Dependency]
	lastUsed atomic.Int64
}

func (s *allDependencyRecordsIterSession) TypeName() string { return "allDependencyRecordsIterSession" }
func (s *allDependencyRecordsIterSession) Touch()           { s.lastUsed.Store(time.Now().UnixNano()) }
func (s *allDependencyRecordsIterSession) LastUsedAt() time.Time {
	return time.Unix(0, s.lastUsed.Load())
}
func (s *allDependencyRecordsIterSession) Close() error { return s.iter.Close() }
