// Code generated by bddgen. DO NOT EDIT.

package rpc

import (
	"context"
	"errors"
	"github.com/steveyegge/beads/internal/storage"
	"github.com/steveyegge/beads/internal/types"
	"net/rpc"
	"time"
)

// rpcIterClose sends an IterClose RPC to the daemon, releasing the server-side
// iterator session. Errors are ignored — the server's idle reaper will clean up
// any session that leaks due to a failed close.
func rpcIterClose(client *rpc.Client, sessionID string) error {
	args := &IterCloseArgs{SessionID: sessionID}
	var reply IterCloseReply
	return client.Call("daemonServer.IterClose", args, &reply)
}

// rpcIssuesIter implements storage.Iter[types.Issue] over net/rpc.
type rpcIssuesIter struct {
	client    *rpc.Client
	sessionID string
	buf       []*types.Issue
	pos       int
	exhausted bool
	err       error
}

func (it *rpcIssuesIter) Next(ctx context.Context) bool {
	if it.exhausted {
		return false
	}
	// Serve from buffer if available.
	if it.pos+1 < len(it.buf) {
		it.pos++
		return true
	}
	// Fetch next batch from server.
	args := &IterNextArgs{SessionID: it.sessionID}
	var reply IterIssuesNextReply
	call := it.client.Go("daemonServer.IterIssuesNext", args, &reply, nil)
	select {
	case <-ctx.Done():
		it.err = ctx.Err()
		it.exhausted = true
		go rpcIterClose(it.client, it.sessionID) //nolint:errcheck
		return false
	case <-call.Done:
	}
	if call.Error != nil {
		it.err = call.Error
		it.exhausted = true
		return false
	}
	if reply.RPCError != nil {
		it.err = decodeRPCError(reply.RPCError)
		it.exhausted = true
		return false
	}
	it.buf = reply.Items
	it.pos = 0
	if reply.Done {
		it.exhausted = true
	}
	return len(it.buf) > 0
}

func (it *rpcIssuesIter) Value() *types.Issue {
	if it.pos < 0 || it.pos >= len(it.buf) {
		return nil
	}
	return it.buf[it.pos]
}

func (it *rpcIssuesIter) Err() error { return it.err }

func (it *rpcIssuesIter) Close() error {
	if !it.exhausted {
		it.exhausted = true
		return rpcIterClose(it.client, it.sessionID)
	}
	return nil
}

var _ storage.Iter[types.Issue] = (*rpcIssuesIter)(nil)

func (c *daemonClient) IterIssues(ctx context.Context, query string, filter types.IssueFilter) (storage.Iter[types.Issue], error) {
	startArgs := &IterIssuesStartArgs{Query: query, Filter: filter}
	var startReply IterStartReply
	if err := c.client.Call("daemonServer.IterIssuesStart", startArgs, &startReply); err != nil {
		return nil, err
	}
	if startReply.RPCError != nil {
		rpcErr := decodeRPCError(startReply.RPCError)
		if errors.Is(rpcErr, storage.ErrTooManyIterators) {
			items, err := c.SearchIssues(ctx, query, filter)
			if err != nil {
				return nil, err
			}
			return storage.NewSliceIter(items), nil
		}
		return nil, rpcErr
	}
	return &rpcIssuesIter{client: c.client, sessionID: startReply.SessionID, pos: -1}, nil
}

// rpcDependentsWithMetadataIter implements storage.Iter[types.IssueWithDependencyMetadata] over net/rpc.
type rpcDependentsWithMetadataIter struct {
	client    *rpc.Client
	sessionID string
	buf       []*types.IssueWithDependencyMetadata
	pos       int
	exhausted bool
	err       error
}

func (it *rpcDependentsWithMetadataIter) Next(ctx context.Context) bool {
	if it.exhausted {
		return false
	}
	// Serve from buffer if available.
	if it.pos+1 < len(it.buf) {
		it.pos++
		return true
	}
	// Fetch next batch from server.
	args := &IterNextArgs{SessionID: it.sessionID}
	var reply IterDependentsWithMetadataNextReply
	call := it.client.Go("daemonServer.IterDependentsWithMetadataNext", args, &reply, nil)
	select {
	case <-ctx.Done():
		it.err = ctx.Err()
		it.exhausted = true
		go rpcIterClose(it.client, it.sessionID) //nolint:errcheck
		return false
	case <-call.Done:
	}
	if call.Error != nil {
		it.err = call.Error
		it.exhausted = true
		return false
	}
	if reply.RPCError != nil {
		it.err = decodeRPCError(reply.RPCError)
		it.exhausted = true
		return false
	}
	it.buf = reply.Items
	it.pos = 0
	if reply.Done {
		it.exhausted = true
	}
	return len(it.buf) > 0
}

func (it *rpcDependentsWithMetadataIter) Value() *types.IssueWithDependencyMetadata {
	if it.pos < 0 || it.pos >= len(it.buf) {
		return nil
	}
	return it.buf[it.pos]
}

func (it *rpcDependentsWithMetadataIter) Err() error { return it.err }

func (it *rpcDependentsWithMetadataIter) Close() error {
	if !it.exhausted {
		it.exhausted = true
		return rpcIterClose(it.client, it.sessionID)
	}
	return nil
}

var _ storage.Iter[types.IssueWithDependencyMetadata] = (*rpcDependentsWithMetadataIter)(nil)

func (c *daemonClient) IterDependentsWithMetadata(ctx context.Context, issueID string) (storage.Iter[types.IssueWithDependencyMetadata], error) {
	startArgs := &IterDependentsWithMetadataStartArgs{IssueID: issueID}
	var startReply IterStartReply
	if err := c.client.Call("daemonServer.IterDependentsWithMetadataStart", startArgs, &startReply); err != nil {
		return nil, err
	}
	if startReply.RPCError != nil {
		rpcErr := decodeRPCError(startReply.RPCError)
		if errors.Is(rpcErr, storage.ErrTooManyIterators) {
			items, err := c.GetDependentsWithMetadata(ctx, issueID)
			if err != nil {
				return nil, err
			}
			return storage.NewSliceIter(items), nil
		}
		return nil, rpcErr
	}
	return &rpcDependentsWithMetadataIter{client: c.client, sessionID: startReply.SessionID, pos: -1}, nil
}

// rpcDependenciesWithMetadataIter implements storage.Iter[types.IssueWithDependencyMetadata] over net/rpc.
type rpcDependenciesWithMetadataIter struct {
	client    *rpc.Client
	sessionID string
	buf       []*types.IssueWithDependencyMetadata
	pos       int
	exhausted bool
	err       error
}

func (it *rpcDependenciesWithMetadataIter) Next(ctx context.Context) bool {
	if it.exhausted {
		return false
	}
	// Serve from buffer if available.
	if it.pos+1 < len(it.buf) {
		it.pos++
		return true
	}
	// Fetch next batch from server.
	args := &IterNextArgs{SessionID: it.sessionID}
	var reply IterDependenciesWithMetadataNextReply
	call := it.client.Go("daemonServer.IterDependenciesWithMetadataNext", args, &reply, nil)
	select {
	case <-ctx.Done():
		it.err = ctx.Err()
		it.exhausted = true
		go rpcIterClose(it.client, it.sessionID) //nolint:errcheck
		return false
	case <-call.Done:
	}
	if call.Error != nil {
		it.err = call.Error
		it.exhausted = true
		return false
	}
	if reply.RPCError != nil {
		it.err = decodeRPCError(reply.RPCError)
		it.exhausted = true
		return false
	}
	it.buf = reply.Items
	it.pos = 0
	if reply.Done {
		it.exhausted = true
	}
	return len(it.buf) > 0
}

func (it *rpcDependenciesWithMetadataIter) Value() *types.IssueWithDependencyMetadata {
	if it.pos < 0 || it.pos >= len(it.buf) {
		return nil
	}
	return it.buf[it.pos]
}

func (it *rpcDependenciesWithMetadataIter) Err() error { return it.err }

func (it *rpcDependenciesWithMetadataIter) Close() error {
	if !it.exhausted {
		it.exhausted = true
		return rpcIterClose(it.client, it.sessionID)
	}
	return nil
}

var _ storage.Iter[types.IssueWithDependencyMetadata] = (*rpcDependenciesWithMetadataIter)(nil)

func (c *daemonClient) IterDependenciesWithMetadata(ctx context.Context, issueID string) (storage.Iter[types.IssueWithDependencyMetadata], error) {
	startArgs := &IterDependenciesWithMetadataStartArgs{IssueID: issueID}
	var startReply IterStartReply
	if err := c.client.Call("daemonServer.IterDependenciesWithMetadataStart", startArgs, &startReply); err != nil {
		return nil, err
	}
	if startReply.RPCError != nil {
		rpcErr := decodeRPCError(startReply.RPCError)
		if errors.Is(rpcErr, storage.ErrTooManyIterators) {
			items, err := c.GetDependenciesWithMetadata(ctx, issueID)
			if err != nil {
				return nil, err
			}
			return storage.NewSliceIter(items), nil
		}
		return nil, rpcErr
	}
	return &rpcDependenciesWithMetadataIter{client: c.client, sessionID: startReply.SessionID, pos: -1}, nil
}

// rpcIssueCommentsIter implements storage.Iter[types.Comment] over net/rpc.
type rpcIssueCommentsIter struct {
	client    *rpc.Client
	sessionID string
	buf       []*types.Comment
	pos       int
	exhausted bool
	err       error
}

func (it *rpcIssueCommentsIter) Next(ctx context.Context) bool {
	if it.exhausted {
		return false
	}
	// Serve from buffer if available.
	if it.pos+1 < len(it.buf) {
		it.pos++
		return true
	}
	// Fetch next batch from server.
	args := &IterNextArgs{SessionID: it.sessionID}
	var reply IterIssueCommentsNextReply
	call := it.client.Go("daemonServer.IterIssueCommentsNext", args, &reply, nil)
	select {
	case <-ctx.Done():
		it.err = ctx.Err()
		it.exhausted = true
		go rpcIterClose(it.client, it.sessionID) //nolint:errcheck
		return false
	case <-call.Done:
	}
	if call.Error != nil {
		it.err = call.Error
		it.exhausted = true
		return false
	}
	if reply.RPCError != nil {
		it.err = decodeRPCError(reply.RPCError)
		it.exhausted = true
		return false
	}
	it.buf = reply.Items
	it.pos = 0
	if reply.Done {
		it.exhausted = true
	}
	return len(it.buf) > 0
}

func (it *rpcIssueCommentsIter) Value() *types.Comment {
	if it.pos < 0 || it.pos >= len(it.buf) {
		return nil
	}
	return it.buf[it.pos]
}

func (it *rpcIssueCommentsIter) Err() error { return it.err }

func (it *rpcIssueCommentsIter) Close() error {
	if !it.exhausted {
		it.exhausted = true
		return rpcIterClose(it.client, it.sessionID)
	}
	return nil
}

var _ storage.Iter[types.Comment] = (*rpcIssueCommentsIter)(nil)

func (c *daemonClient) IterIssueComments(ctx context.Context, issueID string) (storage.Iter[types.Comment], error) {
	startArgs := &IterIssueCommentsStartArgs{IssueID: issueID}
	var startReply IterStartReply
	if err := c.client.Call("daemonServer.IterIssueCommentsStart", startArgs, &startReply); err != nil {
		return nil, err
	}
	if startReply.RPCError != nil {
		rpcErr := decodeRPCError(startReply.RPCError)
		if errors.Is(rpcErr, storage.ErrTooManyIterators) {
			items, err := c.GetIssueComments(ctx, issueID)
			if err != nil {
				return nil, err
			}
			return storage.NewSliceIter(items), nil
		}
		return nil, rpcErr
	}
	return &rpcIssueCommentsIter{client: c.client, sessionID: startReply.SessionID, pos: -1}, nil
}

// rpcEventsIter implements storage.Iter[types.Event] over net/rpc.
type rpcEventsIter struct {
	client    *rpc.Client
	sessionID string
	buf       []*types.Event
	pos       int
	exhausted bool
	err       error
}

func (it *rpcEventsIter) Next(ctx context.Context) bool {
	if it.exhausted {
		return false
	}
	// Serve from buffer if available.
	if it.pos+1 < len(it.buf) {
		it.pos++
		return true
	}
	// Fetch next batch from server.
	args := &IterNextArgs{SessionID: it.sessionID}
	var reply IterEventsNextReply
	call := it.client.Go("daemonServer.IterEventsNext", args, &reply, nil)
	select {
	case <-ctx.Done():
		it.err = ctx.Err()
		it.exhausted = true
		go rpcIterClose(it.client, it.sessionID) //nolint:errcheck
		return false
	case <-call.Done:
	}
	if call.Error != nil {
		it.err = call.Error
		it.exhausted = true
		return false
	}
	if reply.RPCError != nil {
		it.err = decodeRPCError(reply.RPCError)
		it.exhausted = true
		return false
	}
	it.buf = reply.Items
	it.pos = 0
	if reply.Done {
		it.exhausted = true
	}
	return len(it.buf) > 0
}

func (it *rpcEventsIter) Value() *types.Event {
	if it.pos < 0 || it.pos >= len(it.buf) {
		return nil
	}
	return it.buf[it.pos]
}

func (it *rpcEventsIter) Err() error { return it.err }

func (it *rpcEventsIter) Close() error {
	if !it.exhausted {
		it.exhausted = true
		return rpcIterClose(it.client, it.sessionID)
	}
	return nil
}

var _ storage.Iter[types.Event] = (*rpcEventsIter)(nil)

func (c *daemonClient) IterEvents(ctx context.Context, issueID string, limit int) (storage.Iter[types.Event], error) {
	startArgs := &IterEventsStartArgs{IssueID: issueID, Limit: limit}
	var startReply IterStartReply
	if err := c.client.Call("daemonServer.IterEventsStart", startArgs, &startReply); err != nil {
		return nil, err
	}
	if startReply.RPCError != nil {
		rpcErr := decodeRPCError(startReply.RPCError)
		if errors.Is(rpcErr, storage.ErrTooManyIterators) {
			items, err := c.GetEvents(ctx, issueID, limit)
			if err != nil {
				return nil, err
			}
			return storage.NewSliceIter(items), nil
		}
		return nil, rpcErr
	}
	return &rpcEventsIter{client: c.client, sessionID: startReply.SessionID, pos: -1}, nil
}

// rpcAllEventsSinceIter implements storage.Iter[types.Event] over net/rpc.
type rpcAllEventsSinceIter struct {
	client    *rpc.Client
	sessionID string
	buf       []*types.Event
	pos       int
	exhausted bool
	err       error
}

func (it *rpcAllEventsSinceIter) Next(ctx context.Context) bool {
	if it.exhausted {
		return false
	}
	// Serve from buffer if available.
	if it.pos+1 < len(it.buf) {
		it.pos++
		return true
	}
	// Fetch next batch from server.
	args := &IterNextArgs{SessionID: it.sessionID}
	var reply IterAllEventsSinceNextReply
	call := it.client.Go("daemonServer.IterAllEventsSinceNext", args, &reply, nil)
	select {
	case <-ctx.Done():
		it.err = ctx.Err()
		it.exhausted = true
		go rpcIterClose(it.client, it.sessionID) //nolint:errcheck
		return false
	case <-call.Done:
	}
	if call.Error != nil {
		it.err = call.Error
		it.exhausted = true
		return false
	}
	if reply.RPCError != nil {
		it.err = decodeRPCError(reply.RPCError)
		it.exhausted = true
		return false
	}
	it.buf = reply.Items
	it.pos = 0
	if reply.Done {
		it.exhausted = true
	}
	return len(it.buf) > 0
}

func (it *rpcAllEventsSinceIter) Value() *types.Event {
	if it.pos < 0 || it.pos >= len(it.buf) {
		return nil
	}
	return it.buf[it.pos]
}

func (it *rpcAllEventsSinceIter) Err() error { return it.err }

func (it *rpcAllEventsSinceIter) Close() error {
	if !it.exhausted {
		it.exhausted = true
		return rpcIterClose(it.client, it.sessionID)
	}
	return nil
}

var _ storage.Iter[types.Event] = (*rpcAllEventsSinceIter)(nil)

func (c *daemonClient) IterAllEventsSince(ctx context.Context, since time.Time) (storage.Iter[types.Event], error) {
	startArgs := &IterAllEventsSinceStartArgs{Since: since}
	var startReply IterStartReply
	if err := c.client.Call("daemonServer.IterAllEventsSinceStart", startArgs, &startReply); err != nil {
		return nil, err
	}
	if startReply.RPCError != nil {
		rpcErr := decodeRPCError(startReply.RPCError)
		if errors.Is(rpcErr, storage.ErrTooManyIterators) {
			items, err := c.GetAllEventsSince(ctx, since)
			if err != nil {
				return nil, err
			}
			return storage.NewSliceIter(items), nil
		}
		return nil, rpcErr
	}
	return &rpcAllEventsSinceIter{client: c.client, sessionID: startReply.SessionID, pos: -1}, nil
}

// rpcReadyWorkIter implements storage.Iter[types.Issue] over net/rpc.
type rpcReadyWorkIter struct {
	client    *rpc.Client
	sessionID string
	buf       []*types.Issue
	pos       int
	exhausted bool
	err       error
}

func (it *rpcReadyWorkIter) Next(ctx context.Context) bool {
	if it.exhausted {
		return false
	}
	// Serve from buffer if available.
	if it.pos+1 < len(it.buf) {
		it.pos++
		return true
	}
	// Fetch next batch from server.
	args := &IterNextArgs{SessionID: it.sessionID}
	var reply IterReadyWorkNextReply
	call := it.client.Go("daemonServer.IterReadyWorkNext", args, &reply, nil)
	select {
	case <-ctx.Done():
		it.err = ctx.Err()
		it.exhausted = true
		go rpcIterClose(it.client, it.sessionID) //nolint:errcheck
		return false
	case <-call.Done:
	}
	if call.Error != nil {
		it.err = call.Error
		it.exhausted = true
		return false
	}
	if reply.RPCError != nil {
		it.err = decodeRPCError(reply.RPCError)
		it.exhausted = true
		return false
	}
	it.buf = reply.Items
	it.pos = 0
	if reply.Done {
		it.exhausted = true
	}
	return len(it.buf) > 0
}

func (it *rpcReadyWorkIter) Value() *types.Issue {
	if it.pos < 0 || it.pos >= len(it.buf) {
		return nil
	}
	return it.buf[it.pos]
}

func (it *rpcReadyWorkIter) Err() error { return it.err }

func (it *rpcReadyWorkIter) Close() error {
	if !it.exhausted {
		it.exhausted = true
		return rpcIterClose(it.client, it.sessionID)
	}
	return nil
}

var _ storage.Iter[types.Issue] = (*rpcReadyWorkIter)(nil)

func (c *daemonClient) IterReadyWork(ctx context.Context, filter types.WorkFilter) (storage.Iter[types.Issue], error) {
	startArgs := &IterReadyWorkStartArgs{Filter: filter}
	var startReply IterStartReply
	if err := c.client.Call("daemonServer.IterReadyWorkStart", startArgs, &startReply); err != nil {
		return nil, err
	}
	if startReply.RPCError != nil {
		rpcErr := decodeRPCError(startReply.RPCError)
		if errors.Is(rpcErr, storage.ErrTooManyIterators) {
			items, err := c.GetReadyWork(ctx, filter)
			if err != nil {
				return nil, err
			}
			return storage.NewSliceIter(items), nil
		}
		return nil, rpcErr
	}
	return &rpcReadyWorkIter{client: c.client, sessionID: startReply.SessionID, pos: -1}, nil
}

// rpcBlockedIssuesIter implements storage.Iter[types.BlockedIssue] over net/rpc.
type rpcBlockedIssuesIter struct {
	client    *rpc.Client
	sessionID string
	buf       []*types.BlockedIssue
	pos       int
	exhausted bool
	err       error
}

func (it *rpcBlockedIssuesIter) Next(ctx context.Context) bool {
	if it.exhausted {
		return false
	}
	// Serve from buffer if available.
	if it.pos+1 < len(it.buf) {
		it.pos++
		return true
	}
	// Fetch next batch from server.
	args := &IterNextArgs{SessionID: it.sessionID}
	var reply IterBlockedIssuesNextReply
	call := it.client.Go("daemonServer.IterBlockedIssuesNext", args, &reply, nil)
	select {
	case <-ctx.Done():
		it.err = ctx.Err()
		it.exhausted = true
		go rpcIterClose(it.client, it.sessionID) //nolint:errcheck
		return false
	case <-call.Done:
	}
	if call.Error != nil {
		it.err = call.Error
		it.exhausted = true
		return false
	}
	if reply.RPCError != nil {
		it.err = decodeRPCError(reply.RPCError)
		it.exhausted = true
		return false
	}
	it.buf = reply.Items
	it.pos = 0
	if reply.Done {
		it.exhausted = true
	}
	return len(it.buf) > 0
}

func (it *rpcBlockedIssuesIter) Value() *types.BlockedIssue {
	if it.pos < 0 || it.pos >= len(it.buf) {
		return nil
	}
	return it.buf[it.pos]
}

func (it *rpcBlockedIssuesIter) Err() error { return it.err }

func (it *rpcBlockedIssuesIter) Close() error {
	if !it.exhausted {
		it.exhausted = true
		return rpcIterClose(it.client, it.sessionID)
	}
	return nil
}

var _ storage.Iter[types.BlockedIssue] = (*rpcBlockedIssuesIter)(nil)

func (c *daemonClient) IterBlockedIssues(ctx context.Context, filter types.WorkFilter) (storage.Iter[types.BlockedIssue], error) {
	startArgs := &IterBlockedIssuesStartArgs{Filter: filter}
	var startReply IterStartReply
	if err := c.client.Call("daemonServer.IterBlockedIssuesStart", startArgs, &startReply); err != nil {
		return nil, err
	}
	if startReply.RPCError != nil {
		rpcErr := decodeRPCError(startReply.RPCError)
		if errors.Is(rpcErr, storage.ErrTooManyIterators) {
			items, err := c.GetBlockedIssues(ctx, filter)
			if err != nil {
				return nil, err
			}
			return storage.NewSliceIter(items), nil
		}
		return nil, rpcErr
	}
	return &rpcBlockedIssuesIter{client: c.client, sessionID: startReply.SessionID, pos: -1}, nil
}

// rpcWispsIter implements storage.Iter[types.Issue] over net/rpc.
type rpcWispsIter struct {
	client    *rpc.Client
	sessionID string
	buf       []*types.Issue
	pos       int
	exhausted bool
	err       error
}

func (it *rpcWispsIter) Next(ctx context.Context) bool {
	if it.exhausted {
		return false
	}
	// Serve from buffer if available.
	if it.pos+1 < len(it.buf) {
		it.pos++
		return true
	}
	// Fetch next batch from server.
	args := &IterNextArgs{SessionID: it.sessionID}
	var reply IterWispsNextReply
	call := it.client.Go("daemonServer.IterWispsNext", args, &reply, nil)
	select {
	case <-ctx.Done():
		it.err = ctx.Err()
		it.exhausted = true
		go rpcIterClose(it.client, it.sessionID) //nolint:errcheck
		return false
	case <-call.Done:
	}
	if call.Error != nil {
		it.err = call.Error
		it.exhausted = true
		return false
	}
	if reply.RPCError != nil {
		it.err = decodeRPCError(reply.RPCError)
		it.exhausted = true
		return false
	}
	it.buf = reply.Items
	it.pos = 0
	if reply.Done {
		it.exhausted = true
	}
	return len(it.buf) > 0
}

func (it *rpcWispsIter) Value() *types.Issue {
	if it.pos < 0 || it.pos >= len(it.buf) {
		return nil
	}
	return it.buf[it.pos]
}

func (it *rpcWispsIter) Err() error { return it.err }

func (it *rpcWispsIter) Close() error {
	if !it.exhausted {
		it.exhausted = true
		return rpcIterClose(it.client, it.sessionID)
	}
	return nil
}

var _ storage.Iter[types.Issue] = (*rpcWispsIter)(nil)

func (c *daemonClient) IterWisps(ctx context.Context, filter types.WispFilter) (storage.Iter[types.Issue], error) {
	startArgs := &IterWispsStartArgs{Filter: filter}
	var startReply IterStartReply
	if err := c.client.Call("daemonServer.IterWispsStart", startArgs, &startReply); err != nil {
		return nil, err
	}
	if startReply.RPCError != nil {
		rpcErr := decodeRPCError(startReply.RPCError)
		if errors.Is(rpcErr, storage.ErrTooManyIterators) {
			items, err := c.ListWisps(ctx, filter)
			if err != nil {
				return nil, err
			}
			return storage.NewSliceIter(items), nil
		}
		return nil, rpcErr
	}
	return &rpcWispsIter{client: c.client, sessionID: startReply.SessionID, pos: -1}, nil
}

// rpcAllDependencyRecordsIter implements storage.Iter[types.Dependency] over net/rpc.
type rpcAllDependencyRecordsIter struct {
	client    *rpc.Client
	sessionID string
	buf       []*types.Dependency
	pos       int
	exhausted bool
	err       error
}

func (it *rpcAllDependencyRecordsIter) Next(ctx context.Context) bool {
	if it.exhausted {
		return false
	}
	// Serve from buffer if available.
	if it.pos+1 < len(it.buf) {
		it.pos++
		return true
	}
	// Fetch next batch from server.
	args := &IterNextArgs{SessionID: it.sessionID}
	var reply IterAllDependencyRecordsNextReply
	call := it.client.Go("daemonServer.IterAllDependencyRecordsNext", args, &reply, nil)
	select {
	case <-ctx.Done():
		it.err = ctx.Err()
		it.exhausted = true
		go rpcIterClose(it.client, it.sessionID) //nolint:errcheck
		return false
	case <-call.Done:
	}
	if call.Error != nil {
		it.err = call.Error
		it.exhausted = true
		return false
	}
	if reply.RPCError != nil {
		it.err = decodeRPCError(reply.RPCError)
		it.exhausted = true
		return false
	}
	it.buf = reply.Items
	it.pos = 0
	if reply.Done {
		it.exhausted = true
	}
	return len(it.buf) > 0
}

func (it *rpcAllDependencyRecordsIter) Value() *types.Dependency {
	if it.pos < 0 || it.pos >= len(it.buf) {
		return nil
	}
	return it.buf[it.pos]
}

func (it *rpcAllDependencyRecordsIter) Err() error { return it.err }

func (it *rpcAllDependencyRecordsIter) Close() error {
	if !it.exhausted {
		it.exhausted = true
		return rpcIterClose(it.client, it.sessionID)
	}
	return nil
}

var _ storage.Iter[types.Dependency] = (*rpcAllDependencyRecordsIter)(nil)

func (c *daemonClient) IterAllDependencyRecords(ctx context.Context) (storage.Iter[types.Dependency], error) {
	startArgs := &IterAllDependencyRecordsStartArgs{}
	var startReply IterStartReply
	if err := c.client.Call("daemonServer.IterAllDependencyRecordsStart", startArgs, &startReply); err != nil {
		return nil, err
	}
	if startReply.RPCError != nil {
		rpcErr := decodeRPCError(startReply.RPCError)
		// No direct slice fallback for this method.
		return nil, rpcErr
	}
	return &rpcAllDependencyRecordsIter{client: c.client, sessionID: startReply.SessionID, pos: -1}, nil
}
