// Code generated by bddgen. DO NOT EDIT.

package rpc

import (
	"github.com/steveyegge/beads/internal/types"
	"time"
)

// IterIssuesStartArgs is the argument struct for IterIssuesStart.
type IterIssuesStartArgs struct {
	Query  string
	Filter types.IssueFilter
	// BatchSize controls rows per IterXxxNext RPC. 0 uses the daemon default.
	BatchSize int
}

// IterIssuesNextReply is the reply struct for IterIssuesNext.
type IterIssuesNextReply struct {
	Items    []*types.Issue
	Done     bool
	RPCError *RPCError
}

// IterDependentsWithMetadataStartArgs is the argument struct for IterDependentsWithMetadataStart.
type IterDependentsWithMetadataStartArgs struct {
	IssueID string
	// BatchSize controls rows per IterXxxNext RPC. 0 uses the daemon default.
	BatchSize int
}

// IterDependentsWithMetadataNextReply is the reply struct for IterDependentsWithMetadataNext.
type IterDependentsWithMetadataNextReply struct {
	Items    []*types.IssueWithDependencyMetadata
	Done     bool
	RPCError *RPCError
}

// IterDependenciesWithMetadataStartArgs is the argument struct for IterDependenciesWithMetadataStart.
type IterDependenciesWithMetadataStartArgs struct {
	IssueID string
	// BatchSize controls rows per IterXxxNext RPC. 0 uses the daemon default.
	BatchSize int
}

// IterDependenciesWithMetadataNextReply is the reply struct for IterDependenciesWithMetadataNext.
type IterDependenciesWithMetadataNextReply struct {
	Items    []*types.IssueWithDependencyMetadata
	Done     bool
	RPCError *RPCError
}

// IterIssueCommentsStartArgs is the argument struct for IterIssueCommentsStart.
type IterIssueCommentsStartArgs struct {
	IssueID string
	// BatchSize controls rows per IterXxxNext RPC. 0 uses the daemon default.
	BatchSize int
}

// IterIssueCommentsNextReply is the reply struct for IterIssueCommentsNext.
type IterIssueCommentsNextReply struct {
	Items    []*types.Comment
	Done     bool
	RPCError *RPCError
}

// IterEventsStartArgs is the argument struct for IterEventsStart.
type IterEventsStartArgs struct {
	IssueID string
	Limit   int
	// BatchSize controls rows per IterXxxNext RPC. 0 uses the daemon default.
	BatchSize int
}

// IterEventsNextReply is the reply struct for IterEventsNext.
type IterEventsNextReply struct {
	Items    []*types.Event
	Done     bool
	RPCError *RPCError
}

// IterAllEventsSinceStartArgs is the argument struct for IterAllEventsSinceStart.
type IterAllEventsSinceStartArgs struct {
	Since time.Time
	// BatchSize controls rows per IterXxxNext RPC. 0 uses the daemon default.
	BatchSize int
}

// IterAllEventsSinceNextReply is the reply struct for IterAllEventsSinceNext.
type IterAllEventsSinceNextReply struct {
	Items    []*types.Event
	Done     bool
	RPCError *RPCError
}

// IterReadyWorkStartArgs is the argument struct for IterReadyWorkStart.
type IterReadyWorkStartArgs struct {
	Filter types.WorkFilter
	// BatchSize controls rows per IterXxxNext RPC. 0 uses the daemon default.
	BatchSize int
}

// IterReadyWorkNextReply is the reply struct for IterReadyWorkNext.
type IterReadyWorkNextReply struct {
	Items    []*types.Issue
	Done     bool
	RPCError *RPCError
}

// IterBlockedIssuesStartArgs is the argument struct for IterBlockedIssuesStart.
type IterBlockedIssuesStartArgs struct {
	Filter types.WorkFilter
	// BatchSize controls rows per IterXxxNext RPC. 0 uses the daemon default.
	BatchSize int
}

// IterBlockedIssuesNextReply is the reply struct for IterBlockedIssuesNext.
type IterBlockedIssuesNextReply struct {
	Items    []*types.BlockedIssue
	Done     bool
	RPCError *RPCError
}

// IterWispsStartArgs is the argument struct for IterWispsStart.
type IterWispsStartArgs struct {
	Filter types.WispFilter
	// BatchSize controls rows per IterXxxNext RPC. 0 uses the daemon default.
	BatchSize int
}

// IterWispsNextReply is the reply struct for IterWispsNext.
type IterWispsNextReply struct {
	Items    []*types.Issue
	Done     bool
	RPCError *RPCError
}

// IterAllDependencyRecordsStartArgs is the argument struct for IterAllDependencyRecordsStart.
type IterAllDependencyRecordsStartArgs struct {
	// BatchSize controls rows per IterXxxNext RPC. 0 uses the daemon default.
	BatchSize int
}

// IterAllDependencyRecordsNextReply is the reply struct for IterAllDependencyRecordsNext.
type IterAllDependencyRecordsNextReply struct {
	Items    []*types.Dependency
	Done     bool
	RPCError *RPCError
}
