// Code generated by bddgen. DO NOT EDIT.

package rpc

import (
	"context"
	"errors"
	"github.com/steveyegge/beads/internal/storage"
	"os"
	"strconv"
	"time"
)

// daemonServer wraps a storage.Storage for net/rpc dispatch.
type daemonServer struct {
	store   storage.Storage
	root    context.Context
	iterMgr *iterSessionManager
}

func daemonCallContext(root context.Context) (context.Context, context.CancelFunc) {
	timeout := 30 * time.Second
	if v := os.Getenv("BEADS_DAEMON_CALL_TIMEOUT"); v != "" {
		if secs, err := strconv.Atoi(v); err == nil && secs > 0 {
			timeout = time.Duration(secs) * time.Second
		}
	}
	return context.WithTimeout(root, timeout)
}

func encodeRPCError(err error) *RPCError {
	if err == nil {
		return nil
	}
	switch {
	case errors.Is(err, storage.ErrAlreadyClaimed):
		return &RPCError{Kind: "ErrAlreadyClaimed", Msg: err.Error()}
	case errors.Is(err, storage.ErrNotClaimable):
		return &RPCError{Kind: "ErrNotClaimable", Msg: err.Error()}
	case errors.Is(err, storage.ErrNotFound):
		return &RPCError{Kind: "ErrNotFound", Msg: err.Error()}
	case errors.Is(err, storage.ErrNotInitialized):
		return &RPCError{Kind: "ErrNotInitialized", Msg: err.Error()}
	case errors.Is(err, storage.ErrPrefixMismatch):
		return &RPCError{Kind: "ErrPrefixMismatch", Msg: err.Error()}
	case errors.Is(err, storage.ErrTooManyIterators):
		return &RPCError{Kind: "ErrTooManyIterators", Msg: err.Error()}
	case errors.Is(err, storage.ErrIterSessionNotFound):
		return &RPCError{Kind: "ErrIterSessionNotFound", Msg: err.Error()}
	default:
		return &RPCError{Kind: "", Msg: err.Error()}
	}
}

func (s *daemonServer) CreateIssue(args *CreateIssueArgs, reply *CreateIssueReply) error {
	ctx, cancel := daemonCallContext(s.root)
	defer cancel()
	err := s.store.CreateIssue(ctx, args.Issue, args.Actor)
	reply.RPCError = encodeRPCError(err)
	return nil
}

func (s *daemonServer) CreateIssues(args *CreateIssuesArgs, reply *CreateIssuesReply) error {
	ctx, cancel := daemonCallContext(s.root)
	defer cancel()
	err := s.store.CreateIssues(ctx, args.Issues, args.Actor)
	reply.RPCError = encodeRPCError(err)
	return nil
}

func (s *daemonServer) GetIssue(args *GetIssueArgs, reply *GetIssueReply) error {
	ctx, cancel := daemonCallContext(s.root)
	defer cancel()
	r0, err := s.store.GetIssue(ctx, args.Id)
	reply.Issue = r0
	reply.RPCError = encodeRPCError(err)
	return nil
}

func (s *daemonServer) GetIssueByExternalRef(args *GetIssueByExternalRefArgs, reply *GetIssueByExternalRefReply) error {
	ctx, cancel := daemonCallContext(s.root)
	defer cancel()
	r0, err := s.store.GetIssueByExternalRef(ctx, args.ExternalRef)
	reply.Issue = r0
	reply.RPCError = encodeRPCError(err)
	return nil
}

func (s *daemonServer) GetIssuesByIDs(args *GetIssuesByIDsArgs, reply *GetIssuesByIDsReply) error {
	ctx, cancel := daemonCallContext(s.root)
	defer cancel()
	r0, err := s.store.GetIssuesByIDs(ctx, args.Ids)
	reply.Issues = r0
	reply.RPCError = encodeRPCError(err)
	return nil
}

func (s *daemonServer) UpdateIssue(args *UpdateIssueArgs, reply *UpdateIssueReply) error {
	ctx, cancel := daemonCallContext(s.root)
	defer cancel()
	err := s.store.UpdateIssue(ctx, args.Id, args.Updates, args.Actor)
	reply.RPCError = encodeRPCError(err)
	return nil
}

func (s *daemonServer) ReopenIssue(args *ReopenIssueArgs, reply *ReopenIssueReply) error {
	ctx, cancel := daemonCallContext(s.root)
	defer cancel()
	err := s.store.ReopenIssue(ctx, args.Id, args.Reason, args.Actor)
	reply.RPCError = encodeRPCError(err)
	return nil
}

func (s *daemonServer) UpdateIssueType(args *UpdateIssueTypeArgs, reply *UpdateIssueTypeReply) error {
	ctx, cancel := daemonCallContext(s.root)
	defer cancel()
	err := s.store.UpdateIssueType(ctx, args.Id, args.IssueType, args.Actor)
	reply.RPCError = encodeRPCError(err)
	return nil
}

func (s *daemonServer) CloseIssue(args *CloseIssueArgs, reply *CloseIssueReply) error {
	ctx, cancel := daemonCallContext(s.root)
	defer cancel()
	err := s.store.CloseIssue(ctx, args.Id, args.Reason, args.Actor, args.Session)
	reply.RPCError = encodeRPCError(err)
	return nil
}

func (s *daemonServer) DeleteIssue(args *DeleteIssueArgs, reply *DeleteIssueReply) error {
	ctx, cancel := daemonCallContext(s.root)
	defer cancel()
	err := s.store.DeleteIssue(ctx, args.Id)
	reply.RPCError = encodeRPCError(err)
	return nil
}

func (s *daemonServer) SearchIssues(args *SearchIssuesArgs, reply *SearchIssuesReply) error {
	ctx, cancel := daemonCallContext(s.root)
	defer cancel()
	r0, err := s.store.SearchIssues(ctx, args.Query, args.Filter)
	reply.Issues = r0
	reply.RPCError = encodeRPCError(err)
	return nil
}

func (s *daemonServer) AddDependency(args *AddDependencyArgs, reply *AddDependencyReply) error {
	ctx, cancel := daemonCallContext(s.root)
	defer cancel()
	err := s.store.AddDependency(ctx, args.Dep, args.Actor)
	reply.RPCError = encodeRPCError(err)
	return nil
}

func (s *daemonServer) RemoveDependency(args *RemoveDependencyArgs, reply *RemoveDependencyReply) error {
	ctx, cancel := daemonCallContext(s.root)
	defer cancel()
	err := s.store.RemoveDependency(ctx, args.IssueID, args.DependsOnID, args.Actor)
	reply.RPCError = encodeRPCError(err)
	return nil
}

func (s *daemonServer) GetDependencies(args *GetDependenciesArgs, reply *GetDependenciesReply) error {
	ctx, cancel := daemonCallContext(s.root)
	defer cancel()
	r0, err := s.store.GetDependencies(ctx, args.IssueID)
	reply.Issues = r0
	reply.RPCError = encodeRPCError(err)
	return nil
}

func (s *daemonServer) GetDependents(args *GetDependentsArgs, reply *GetDependentsReply) error {
	ctx, cancel := daemonCallContext(s.root)
	defer cancel()
	r0, err := s.store.GetDependents(ctx, args.IssueID)
	reply.Issues = r0
	reply.RPCError = encodeRPCError(err)
	return nil
}

func (s *daemonServer) GetDependenciesWithMetadata(args *GetDependenciesWithMetadataArgs, reply *GetDependenciesWithMetadataReply) error {
	ctx, cancel := daemonCallContext(s.root)
	defer cancel()
	r0, err := s.store.GetDependenciesWithMetadata(ctx, args.IssueID)
	reply.IssueWithDependencyMetadatas = r0
	reply.RPCError = encodeRPCError(err)
	return nil
}

func (s *daemonServer) GetDependentsWithMetadata(args *GetDependentsWithMetadataArgs, reply *GetDependentsWithMetadataReply) error {
	ctx, cancel := daemonCallContext(s.root)
	defer cancel()
	r0, err := s.store.GetDependentsWithMetadata(ctx, args.IssueID)
	reply.IssueWithDependencyMetadatas = r0
	reply.RPCError = encodeRPCError(err)
	return nil
}

func (s *daemonServer) GetDependencyTree(args *GetDependencyTreeArgs, reply *GetDependencyTreeReply) error {
	ctx, cancel := daemonCallContext(s.root)
	defer cancel()
	r0, err := s.store.GetDependencyTree(ctx, args.IssueID, args.MaxDepth, args.ShowAllPaths, args.Reverse)
	reply.TreeNodes = r0
	reply.RPCError = encodeRPCError(err)
	return nil
}

func (s *daemonServer) AddLabel(args *AddLabelArgs, reply *AddLabelReply) error {
	ctx, cancel := daemonCallContext(s.root)
	defer cancel()
	err := s.store.AddLabel(ctx, args.IssueID, args.Label, args.Actor)
	reply.RPCError = encodeRPCError(err)
	return nil
}

func (s *daemonServer) RemoveLabel(args *RemoveLabelArgs, reply *RemoveLabelReply) error {
	ctx, cancel := daemonCallContext(s.root)
	defer cancel()
	err := s.store.RemoveLabel(ctx, args.IssueID, args.Label, args.Actor)
	reply.RPCError = encodeRPCError(err)
	return nil
}

func (s *daemonServer) GetLabels(args *GetLabelsArgs, reply *GetLabelsReply) error {
	ctx, cancel := daemonCallContext(s.root)
	defer cancel()
	r0, err := s.store.GetLabels(ctx, args.IssueID)
	reply.strings = r0
	reply.RPCError = encodeRPCError(err)
	return nil
}

func (s *daemonServer) GetIssuesByLabel(args *GetIssuesByLabelArgs, reply *GetIssuesByLabelReply) error {
	ctx, cancel := daemonCallContext(s.root)
	defer cancel()
	r0, err := s.store.GetIssuesByLabel(ctx, args.Label)
	reply.Issues = r0
	reply.RPCError = encodeRPCError(err)
	return nil
}

func (s *daemonServer) GetReadyWork(args *GetReadyWorkArgs, reply *GetReadyWorkReply) error {
	ctx, cancel := daemonCallContext(s.root)
	defer cancel()
	r0, err := s.store.GetReadyWork(ctx, args.Filter)
	reply.Issues = r0
	reply.RPCError = encodeRPCError(err)
	return nil
}

func (s *daemonServer) GetBlockedIssues(args *GetBlockedIssuesArgs, reply *GetBlockedIssuesReply) error {
	ctx, cancel := daemonCallContext(s.root)
	defer cancel()
	r0, err := s.store.GetBlockedIssues(ctx, args.Filter)
	reply.BlockedIssues = r0
	reply.RPCError = encodeRPCError(err)
	return nil
}

func (s *daemonServer) GetEpicsEligibleForClosure(args *GetEpicsEligibleForClosureArgs, reply *GetEpicsEligibleForClosureReply) error {
	ctx, cancel := daemonCallContext(s.root)
	defer cancel()
	r0, err := s.store.GetEpicsEligibleForClosure(ctx)
	reply.EpicStatuss = r0
	reply.RPCError = encodeRPCError(err)
	return nil
}

func (s *daemonServer) ListWisps(args *ListWispsArgs, reply *ListWispsReply) error {
	ctx, cancel := daemonCallContext(s.root)
	defer cancel()
	r0, err := s.store.ListWisps(ctx, args.Filter)
	reply.Issues = r0
	reply.RPCError = encodeRPCError(err)
	return nil
}

func (s *daemonServer) AddIssueComment(args *AddIssueCommentArgs, reply *AddIssueCommentReply) error {
	ctx, cancel := daemonCallContext(s.root)
	defer cancel()
	r0, err := s.store.AddIssueComment(ctx, args.IssueID, args.Author, args.Text)
	reply.Comment = r0
	reply.RPCError = encodeRPCError(err)
	return nil
}

func (s *daemonServer) GetIssueComments(args *GetIssueCommentsArgs, reply *GetIssueCommentsReply) error {
	ctx, cancel := daemonCallContext(s.root)
	defer cancel()
	r0, err := s.store.GetIssueComments(ctx, args.IssueID)
	reply.Comments = r0
	reply.RPCError = encodeRPCError(err)
	return nil
}

func (s *daemonServer) GetEvents(args *GetEventsArgs, reply *GetEventsReply) error {
	ctx, cancel := daemonCallContext(s.root)
	defer cancel()
	r0, err := s.store.GetEvents(ctx, args.IssueID, args.Limit)
	reply.Events = r0
	reply.RPCError = encodeRPCError(err)
	return nil
}

func (s *daemonServer) GetAllEventsSince(args *GetAllEventsSinceArgs, reply *GetAllEventsSinceReply) error {
	ctx, cancel := daemonCallContext(s.root)
	defer cancel()
	r0, err := s.store.GetAllEventsSince(ctx, args.Since)
	reply.Events = r0
	reply.RPCError = encodeRPCError(err)
	return nil
}

func (s *daemonServer) GetStatistics(args *GetStatisticsArgs, reply *GetStatisticsReply) error {
	ctx, cancel := daemonCallContext(s.root)
	defer cancel()
	r0, err := s.store.GetStatistics(ctx)
	reply.Statistics = r0
	reply.RPCError = encodeRPCError(err)
	return nil
}

func (s *daemonServer) SetConfig(args *SetConfigArgs, reply *SetConfigReply) error {
	ctx, cancel := daemonCallContext(s.root)
	defer cancel()
	err := s.store.SetConfig(ctx, args.Key, args.Value)
	reply.RPCError = encodeRPCError(err)
	return nil
}

func (s *daemonServer) GetConfig(args *GetConfigArgs, reply *GetConfigReply) error {
	ctx, cancel := daemonCallContext(s.root)
	defer cancel()
	r0, err := s.store.GetConfig(ctx, args.Key)
	reply.Value = r0
	reply.RPCError = encodeRPCError(err)
	return nil
}

func (s *daemonServer) GetAllConfig(args *GetAllConfigArgs, reply *GetAllConfigReply) error {
	ctx, cancel := daemonCallContext(s.root)
	defer cancel()
	r0, err := s.store.GetAllConfig(ctx)
	reply.Data = r0
	reply.RPCError = encodeRPCError(err)
	return nil
}

func (s *daemonServer) SetLocalMetadata(args *SetLocalMetadataArgs, reply *SetLocalMetadataReply) error {
	ctx, cancel := daemonCallContext(s.root)
	defer cancel()
	err := s.store.SetLocalMetadata(ctx, args.Key, args.Value)
	reply.RPCError = encodeRPCError(err)
	return nil
}

func (s *daemonServer) GetLocalMetadata(args *GetLocalMetadataArgs, reply *GetLocalMetadataReply) error {
	ctx, cancel := daemonCallContext(s.root)
	defer cancel()
	r0, err := s.store.GetLocalMetadata(ctx, args.Key)
	reply.Value = r0
	reply.RPCError = encodeRPCError(err)
	return nil
}

func (s *daemonServer) MergeSlotCreate(args *MergeSlotCreateArgs, reply *MergeSlotCreateReply) error {
	ctx, cancel := daemonCallContext(s.root)
	defer cancel()
	r0, err := s.store.MergeSlotCreate(ctx, args.Actor)
	reply.Issue = r0
	reply.RPCError = encodeRPCError(err)
	return nil
}

func (s *daemonServer) MergeSlotCheck(args *MergeSlotCheckArgs, reply *MergeSlotCheckReply) error {
	ctx, cancel := daemonCallContext(s.root)
	defer cancel()
	r0, err := s.store.MergeSlotCheck(ctx)
	reply.MergeSlotStatus = r0
	reply.RPCError = encodeRPCError(err)
	return nil
}

func (s *daemonServer) MergeSlotAcquire(args *MergeSlotAcquireArgs, reply *MergeSlotAcquireReply) error {
	ctx, cancel := daemonCallContext(s.root)
	defer cancel()
	r0, err := s.store.MergeSlotAcquire(ctx, args.Holder, args.Actor, args.Wait)
	reply.MergeSlotResult = r0
	reply.RPCError = encodeRPCError(err)
	return nil
}

func (s *daemonServer) MergeSlotRelease(args *MergeSlotReleaseArgs, reply *MergeSlotReleaseReply) error {
	ctx, cancel := daemonCallContext(s.root)
	defer cancel()
	err := s.store.MergeSlotRelease(ctx, args.Holder, args.Actor)
	reply.RPCError = encodeRPCError(err)
	return nil
}

func (s *daemonServer) SlotSet(args *SlotSetArgs, reply *SlotSetReply) error {
	ctx, cancel := daemonCallContext(s.root)
	defer cancel()
	err := s.store.SlotSet(ctx, args.IssueID, args.Key, args.Value, args.Actor)
	reply.RPCError = encodeRPCError(err)
	return nil
}

func (s *daemonServer) SlotGet(args *SlotGetArgs, reply *SlotGetReply) error {
	ctx, cancel := daemonCallContext(s.root)
	defer cancel()
	r0, err := s.store.SlotGet(ctx, args.IssueID, args.Key)
	reply.Value = r0
	reply.RPCError = encodeRPCError(err)
	return nil
}

func (s *daemonServer) SlotClear(args *SlotClearArgs, reply *SlotClearReply) error {
	ctx, cancel := daemonCallContext(s.root)
	defer cancel()
	err := s.store.SlotClear(ctx, args.IssueID, args.Key, args.Actor)
	reply.RPCError = encodeRPCError(err)
	return nil
}
