// Code generated by bddgen. DO NOT EDIT.

package rpc

import (
	"github.com/steveyegge/beads/internal/storage"
	"github.com/steveyegge/beads/internal/types"
	"time"
)

// RPCError carries sentinel error identity across net/rpc boundaries.
type RPCError struct {
	Kind string
	Msg  string
}

type CreateIssueArgs struct {
	Issue *types.Issue
	Actor string
}

type CreateIssueReply struct {
	RPCError *RPCError
}

type CreateIssuesArgs struct {
	Issues []*types.Issue
	Actor  string
}

type CreateIssuesReply struct {
	RPCError *RPCError
}

type GetIssueArgs struct {
	Id string
}

type GetIssueReply struct {
	Issue    *types.Issue
	RPCError *RPCError
}

type GetIssueByExternalRefArgs struct {
	ExternalRef string
}

type GetIssueByExternalRefReply struct {
	Issue    *types.Issue
	RPCError *RPCError
}

type GetIssuesByIDsArgs struct {
	Ids []string
}

type GetIssuesByIDsReply struct {
	Issues   []*types.Issue
	RPCError *RPCError
}

type UpdateIssueArgs struct {
	Id      string
	Updates map[string]interface{}
	Actor   string
}

type UpdateIssueReply struct {
	RPCError *RPCError
}

type ReopenIssueArgs struct {
	Id     string
	Reason string
	Actor  string
}

type ReopenIssueReply struct {
	RPCError *RPCError
}

type UpdateIssueTypeArgs struct {
	Id        string
	IssueType string
	Actor     string
}

type UpdateIssueTypeReply struct {
	RPCError *RPCError
}

type CloseIssueArgs struct {
	Id      string
	Reason  string
	Actor   string
	Session string
}

type CloseIssueReply struct {
	RPCError *RPCError
}

type DeleteIssueArgs struct {
	Id string
}

type DeleteIssueReply struct {
	RPCError *RPCError
}

type SearchIssuesArgs struct {
	Query  string
	Filter types.IssueFilter
}

type SearchIssuesReply struct {
	Issues   []*types.Issue
	RPCError *RPCError
}

type AddDependencyArgs struct {
	Dep   *types.Dependency
	Actor string
}

type AddDependencyReply struct {
	RPCError *RPCError
}

type RemoveDependencyArgs struct {
	IssueID     string
	DependsOnID string
	Actor       string
}

type RemoveDependencyReply struct {
	RPCError *RPCError
}

type GetDependenciesArgs struct {
	IssueID string
}

type GetDependenciesReply struct {
	Issues   []*types.Issue
	RPCError *RPCError
}

type GetDependentsArgs struct {
	IssueID string
}

type GetDependentsReply struct {
	Issues   []*types.Issue
	RPCError *RPCError
}

type GetDependenciesWithMetadataArgs struct {
	IssueID string
}

type GetDependenciesWithMetadataReply struct {
	IssueWithDependencyMetadatas []*types.IssueWithDependencyMetadata
	RPCError                     *RPCError
}

type GetDependentsWithMetadataArgs struct {
	IssueID string
}

type GetDependentsWithMetadataReply struct {
	IssueWithDependencyMetadatas []*types.IssueWithDependencyMetadata
	RPCError                     *RPCError
}

type GetDependencyTreeArgs struct {
	IssueID      string
	MaxDepth     int
	ShowAllPaths bool
	Reverse      bool
}

type GetDependencyTreeReply struct {
	TreeNodes []*types.TreeNode
	RPCError  *RPCError
}

type AddLabelArgs struct {
	IssueID string
	Label   string
	Actor   string
}

type AddLabelReply struct {
	RPCError *RPCError
}

type RemoveLabelArgs struct {
	IssueID string
	Label   string
	Actor   string
}

type RemoveLabelReply struct {
	RPCError *RPCError
}

type GetLabelsArgs struct {
	IssueID string
}

type GetLabelsReply struct {
	strings  []string
	RPCError *RPCError
}

type GetIssuesByLabelArgs struct {
	Label string
}

type GetIssuesByLabelReply struct {
	Issues   []*types.Issue
	RPCError *RPCError
}

type GetReadyWorkArgs struct {
	Filter types.WorkFilter
}

type GetReadyWorkReply struct {
	Issues   []*types.Issue
	RPCError *RPCError
}

type GetBlockedIssuesArgs struct {
	Filter types.WorkFilter
}

type GetBlockedIssuesReply struct {
	BlockedIssues []*types.BlockedIssue
	RPCError      *RPCError
}

type GetEpicsEligibleForClosureArgs struct {
}

type GetEpicsEligibleForClosureReply struct {
	EpicStatuss []*types.EpicStatus
	RPCError    *RPCError
}

type ListWispsArgs struct {
	Filter types.WispFilter
}

type ListWispsReply struct {
	Issues   []*types.Issue
	RPCError *RPCError
}

type AddIssueCommentArgs struct {
	IssueID string
	Author  string
	Text    string
}

type AddIssueCommentReply struct {
	Comment  *types.Comment
	RPCError *RPCError
}

type GetIssueCommentsArgs struct {
	IssueID string
}

type GetIssueCommentsReply struct {
	Comments []*types.Comment
	RPCError *RPCError
}

type GetEventsArgs struct {
	IssueID string
	Limit   int
}

type GetEventsReply struct {
	Events   []*types.Event
	RPCError *RPCError
}

type GetAllEventsSinceArgs struct {
	Since time.Time
}

type GetAllEventsSinceReply struct {
	Events   []*types.Event
	RPCError *RPCError
}

type GetStatisticsArgs struct {
}

type GetStatisticsReply struct {
	Statistics *types.Statistics
	RPCError   *RPCError
}

type SetConfigArgs struct {
	Key   string
	Value string
}

type SetConfigReply struct {
	RPCError *RPCError
}

type GetConfigArgs struct {
	Key string
}

type GetConfigReply struct {
	Value    string
	RPCError *RPCError
}

type GetAllConfigArgs struct {
}

type GetAllConfigReply struct {
	Data     map[string]string
	RPCError *RPCError
}

type SetLocalMetadataArgs struct {
	Key   string
	Value string
}

type SetLocalMetadataReply struct {
	RPCError *RPCError
}

type GetLocalMetadataArgs struct {
	Key string
}

type GetLocalMetadataReply struct {
	Value    string
	RPCError *RPCError
}

type MergeSlotCreateArgs struct {
	Actor string
}

type MergeSlotCreateReply struct {
	Issue    *types.Issue
	RPCError *RPCError
}

type MergeSlotCheckArgs struct {
}

type MergeSlotCheckReply struct {
	MergeSlotStatus *storage.MergeSlotStatus
	RPCError        *RPCError
}

type MergeSlotAcquireArgs struct {
	Holder string
	Actor  string
	Wait   bool
}

type MergeSlotAcquireReply struct {
	MergeSlotResult *storage.MergeSlotResult
	RPCError        *RPCError
}

type MergeSlotReleaseArgs struct {
	Holder string
	Actor  string
}

type MergeSlotReleaseReply struct {
	RPCError *RPCError
}

type SlotSetArgs struct {
	IssueID string
	Key     string
	Value   string
	Actor   string
}

type SlotSetReply struct {
	RPCError *RPCError
}

type SlotGetArgs struct {
	IssueID string
	Key     string
}

type SlotGetReply struct {
	Value    string
	RPCError *RPCError
}

type SlotClearArgs struct {
	IssueID string
	Key     string
	Actor   string
}

type SlotClearReply struct {
	RPCError *RPCError
}
