#!/usr/bin/env python3
"""Collect GitHub Actions timing data and render CI timing reports.

The script intentionally depends only on Python's standard library and the
GitHub CLI. It reads recent workflow runs plus per-run job metadata, then writes
Markdown and HTML summaries that can be regenerated by maintainers.
"""

from __future__ import annotations

import argparse
import concurrent.futures
import datetime as dt
import html
import json
import math
import os
import re
import statistics
import subprocess
import sys
from collections import Counter, defaultdict
from pathlib import Path
from typing import Any


WORKFLOW_FILES = [
    ".github/workflows/ci.yml",
    ".github/workflows/cross-version-smoke.yml",
    ".github/workflows/regression.yml",
    ".github/workflows/nix-build.yml",
    ".github/workflows/nightly.yml",
    ".github/workflows/migration-test.yml",
]


def parse_time(value: str | None) -> dt.datetime | None:
    if not value:
        return None
    return dt.datetime.fromisoformat(value.replace("Z", "+00:00"))


def minutes_between(start: str | None, end: str | None) -> float | None:
    a = parse_time(start)
    b = parse_time(end)
    if not a or not b:
        return None
    return max(0.0, (b - a).total_seconds() / 60.0)


def percentile(values: list[float], pct: float) -> float | None:
    if not values:
        return None
    ordered = sorted(values)
    index = max(0, math.ceil((pct / 100.0) * len(ordered)) - 1)
    return ordered[index]


def fmt_minutes(value: float | None) -> str:
    if value is None:
        return "n/a"
    if value < 1:
        return f"{value * 60:.0f}s"
    return f"{value:.1f}m"


def fmt_pct(value: float) -> str:
    return f"{value:.0%}"


def gh_json(args: list[str]) -> Any:
    command = ["gh", *args]
    try:
        proc = subprocess.run(command, check=True, text=True, capture_output=True)
    except subprocess.CalledProcessError as exc:
        sys.stderr.write(exc.stderr)
        raise SystemExit(f"gh command failed: {' '.join(command)}") from exc
    return json.loads(proc.stdout or "null")


def job_key(name: str) -> str:
    name = re.sub(r"Test \(Embedded Dolt Cmd \d+/\d+\)", "Test (Embedded Dolt Cmd shard)", name)
    name = re.sub(r"Upgrade smoke \(v[^)]+ candidate\)", "Upgrade smoke (version shard)", name)
    return name


def collect_runs(repo: str, limit: int) -> list[dict[str, Any]]:
    fields = [
        "databaseId",
        "workflowName",
        "event",
        "status",
        "conclusion",
        "createdAt",
        "startedAt",
        "updatedAt",
        "headBranch",
        "displayTitle",
        "url",
    ]
    return gh_json(
        [
            "run",
            "list",
            "--repo",
            repo,
            "--limit",
            str(limit),
            "--json",
            ",".join(fields),
        ]
    )


def collect_jobs(repo: str, run_id: int) -> list[dict[str, Any]]:
    endpoint = f"repos/{repo}/actions/runs/{run_id}/jobs"
    data = gh_json(["api", "--method", "GET", endpoint, "--paginate", "-f", "per_page=100"])
    if isinstance(data, list):
        jobs: list[dict[str, Any]] = []
        for page in data:
            jobs.extend(page.get("jobs", []))
        return jobs
    return data.get("jobs", [])


def workflow_file_summary(root: Path) -> list[tuple[str, str]]:
    rows = []
    for rel in WORKFLOW_FILES:
        path = root / rel
        if not path.exists():
            continue
        name = rel
        for line in path.read_text(encoding="utf-8").splitlines():
            if line.startswith("name:"):
                name = line.split(":", 1)[1].strip()
                break
        rows.append((name, rel))
    return rows


def summarize(runs: list[dict[str, Any]], jobs_by_run: dict[int, list[dict[str, Any]]]) -> dict[str, Any]:
    completed = [r for r in runs if r.get("status") == "completed"]
    timed = []
    job_rows = []
    queue_values = []
    run_queue_values = []

    for run in completed:
        wall = minutes_between(run.get("createdAt"), run.get("updatedAt"))
        run_queue = minutes_between(run.get("createdAt"), run.get("startedAt"))
        if run_queue is not None:
            run_queue_values.append(run_queue)
        if wall is not None:
            run = dict(run)
            run["wall_minutes"] = wall
            run["queue_minutes"] = run_queue
            timed.append(run)

        for job in jobs_by_run.get(run["databaseId"], []):
            duration = minutes_between(job.get("started_at"), job.get("completed_at"))
            queue = minutes_between(job.get("created_at"), job.get("started_at"))
            if queue is not None:
                queue_values.append(queue)
            job_rows.append(
                {
                    "run_id": run["databaseId"],
                    "workflow": run.get("workflowName") or "",
                    "event": run.get("event") or "",
                    "run_conclusion": run.get("conclusion") or "",
                    "run_wall_minutes": wall,
                    "name": job.get("name") or "",
                    "key": job_key(job.get("name") or ""),
                    "runner": job.get("runner_name") or "",
                    "status": job.get("status") or "",
                    "conclusion": job.get("conclusion") or "",
                    "duration_minutes": duration,
                    "queue_minutes": queue,
                    "started_at": job.get("started_at"),
                    "completed_at": job.get("completed_at"),
                    "html_url": job.get("html_url") or "",
                }
            )

    by_workflow_event: dict[tuple[str, str], list[dict[str, Any]]] = defaultdict(list)
    for run in timed:
        if run.get("conclusion") == "cancelled":
            continue
        by_workflow_event[(run.get("workflowName") or "", run.get("event") or "")].append(run)

    job_agg: dict[str, dict[str, Any]] = defaultdict(
        lambda: {
            "durations": [],
            "queues": [],
            "count": 0,
            "failures": 0,
            "cancelled": 0,
            "non_success": 0,
            "skipped": 0,
            "workflow": Counter(),
            "event": Counter(),
        }
    )
    for row in job_rows:
        key = row["key"]
        agg = job_agg[key]
        agg["count"] += 1
        agg["workflow"][row["workflow"]] += 1
        agg["event"][row["event"]] += 1
        if row["duration_minutes"] is not None:
            agg["durations"].append(row["duration_minutes"])
        if row["queue_minutes"] is not None:
            agg["queues"].append(row["queue_minutes"])
        if row["conclusion"] not in ("", "success", "skipped"):
            agg["non_success"] += 1
        if row["conclusion"] == "failure":
            agg["failures"] += 1
        if row["conclusion"] == "cancelled":
            agg["cancelled"] += 1
        if row["conclusion"] == "skipped":
            agg["skipped"] += 1

    return {
        "runs": runs,
        "completed": completed,
        "timed": timed,
        "job_rows": job_rows,
        "by_workflow_event": by_workflow_event,
        "job_agg": job_agg,
        "queue_values": queue_values,
        "run_queue_values": run_queue_values,
    }


def critical_path_rows(summary: dict[str, Any]) -> list[tuple[str, int, float | None]]:
    """Return jobs that most often finished last in successful PR CI runs."""
    by_run: dict[int, list[dict[str, Any]]] = defaultdict(list)
    successful_pr_ci_runs = {
        run["databaseId"]
        for run in summary["timed"]
        if run.get("workflowName") == "CI" and run.get("event") == "pull_request" and run.get("conclusion") == "success"
    }
    for row in summary["job_rows"]:
        if row["run_id"] in successful_pr_ci_runs and row["completed_at"] and row["conclusion"] == "success":
            by_run[row["run_id"]].append(row)

    tails: dict[str, list[float]] = defaultdict(list)
    for rows in by_run.values():
        latest = max(rows, key=lambda row: parse_time(row["completed_at"]) or dt.datetime.min.replace(tzinfo=dt.timezone.utc))
        if latest["duration_minutes"] is not None:
            tails[latest["key"]].append(latest["duration_minutes"])

    return sorted(
        ((name, len(values), percentile(values, 50)) for name, values in tails.items()),
        key=lambda item: item[1],
        reverse=True,
    )


def render_markdown(repo: str, run_limit: int, summary: dict[str, Any], workflows: list[tuple[str, str]]) -> str:
    now = dt.datetime.now(dt.timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    timed = summary["timed"]
    completed = summary["completed"]
    job_rows = summary["job_rows"]
    by_workflow_event = summary["by_workflow_event"]
    job_agg = summary["job_agg"]
    runs = summary["runs"]

    successful_ci_pr = [
        r["wall_minutes"]
        for r in timed
        if r.get("workflowName") == "CI" and r.get("event") == "pull_request" and r.get("conclusion") == "success"
    ]
    successful_all = [r["wall_minutes"] for r in timed if r.get("conclusion") == "success"]
    cancelled = [r for r in completed if r.get("conclusion") == "cancelled"]
    failures = [r for r in completed if r.get("conclusion") not in ("success", "cancelled", "skipped")]
    in_progress = [r for r in runs if r.get("status") != "completed"]

    lines = [
        "# CI Timing Report",
        "",
        f"Generated: {now}",
        "",
        f"Repository: `{repo}`",
        "",
        f"Command: `python3 scripts/ci/ci_timing_report.py --repo {repo} --runs {run_limit} --out-dir docs/reports`",
        "",
        "## Data Set",
        "",
        f"- Recent workflow runs requested: {run_limit}",
        f"- Workflow runs returned: {len(runs)}",
        f"- Completed runs analyzed: {len(completed)}",
        f"- Jobs analyzed: {len(job_rows)}",
        f"- Incomplete runs at collection time: {len(in_progress)}",
        f"- Cancelled runs: {len(cancelled)}",
        f"- Failed/non-success non-cancelled runs: {len(failures)}",
        f"- Successful PR CI wall-clock P50/P95: {fmt_minutes(percentile(successful_ci_pr, 50))} / {fmt_minutes(percentile(successful_ci_pr, 95))}",
        f"- All successful workflow wall-clock P50/P95: {fmt_minutes(percentile(successful_all, 50))} / {fmt_minutes(percentile(successful_all, 95))}",
        f"- Run queue P50/P95: {fmt_minutes(percentile(summary['run_queue_values'], 50))} / {fmt_minutes(percentile(summary['run_queue_values'], 95))}",
        f"- Job queue P50/P95: {fmt_minutes(percentile(summary['queue_values'], 50))} / {fmt_minutes(percentile(summary['queue_values'], 95))}",
        "",
        "GitHub `run_started_at` is currently equal to `created_at` for most runs, so run-level queue time is less useful than per-job queue time. Job queue time uses `job.created_at` to `job.started_at` when present.",
        "",
        "## Checked Workflow Files",
        "",
        "| Workflow | Local file |",
        "|---|---|",
    ]
    for name, rel in workflows:
        lines.append(f"| {name} | `{rel}` |")

    lines.extend(["", "## Wall-Clock by Workflow and Event", "", "| Workflow | Event | Runs | Success | P50 | P95 | Max |", "|---|---:|---:|---:|---:|---:|---:|"])
    for (workflow, event), rows in sorted(by_workflow_event.items(), key=lambda item: (item[0][0], item[0][1])):
        durations = [r["wall_minutes"] for r in rows]
        successes = sum(1 for r in rows if r.get("conclusion") == "success")
        lines.append(
            f"| {workflow} | {event} | {len(rows)} | {successes} | {fmt_minutes(percentile(durations, 50))} | {fmt_minutes(percentile(durations, 95))} | {fmt_minutes(max(durations) if durations else None)} |"
        )

    slow_jobs = sorted(
        (
            (key, agg)
            for key, agg in job_agg.items()
            if agg["durations"]
        ),
        key=lambda item: percentile(item[1]["durations"], 95) or 0,
        reverse=True,
    )[:20]
    lines.extend(["", "## Slowest Jobs", "", "| Job | Runs | Workflow | P50 | P95 | Max | Failure rate | Queue P95 |", "|---|---:|---|---:|---:|---:|---:|---:|"])
    for key, agg in slow_jobs:
        durations = agg["durations"]
        queues = agg["queues"]
        workflow = agg["workflow"].most_common(1)[0][0] if agg["workflow"] else ""
        fail_rate = agg["non_success"] / agg["count"] if agg["count"] else 0
        lines.append(
            f"| {key} | {agg['count']} | {workflow} | {fmt_minutes(percentile(durations, 50))} | {fmt_minutes(percentile(durations, 95))} | {fmt_minutes(max(durations))} | {fmt_pct(fail_rate)} | {fmt_minutes(percentile(queues, 95))} |"
        )

    lines.extend(
        [
            "",
            "## Critical Path",
            "",
            "For successful PR CI runs, the tail job is the last successful job to complete in the workflow run. This is the best available proxy for the Actions critical path from public run/job metadata.",
            "",
            "| Tail job | Runs ending here | Median job duration |",
            "|---|---:|---:|",
        ]
    )
    cp_rows = critical_path_rows(summary)
    if cp_rows:
        for name, count, median_duration in cp_rows[:10]:
            lines.append(f"| {name} | {count} | {fmt_minutes(median_duration)} |")
    else:
        lines.append("| None observed | 0 | n/a |")

    failing_jobs = sorted(
        ((key, agg) for key, agg in job_agg.items() if agg["failures"] or agg["cancelled"]),
        key=lambda item: (item[1]["failures"], item[1]["cancelled"], percentile(item[1]["durations"], 95) or 0),
        reverse=True,
    )[:15]
    lines.extend(
        [
            "",
            "## Failure and Flakiness Suspects",
            "",
            "Failures are stronger flake suspects than cancellations; cancellations often come from concurrency replacing older PR runs.",
            "",
            "| Job | Failures | Cancels | Runs | Failure rate | Non-success rate | P95 duration |",
            "|---|---:|---:|---:|---:|---:|---:|",
        ]
    )
    if failing_jobs:
        for key, agg in failing_jobs:
            lines.append(
                f"| {key} | {agg['failures']} | {agg['cancelled']} | {agg['count']} | {fmt_pct(agg['failures'] / agg['count'])} | {fmt_pct(agg['non_success'] / agg['count'])} | {fmt_minutes(percentile(agg['durations'], 95))} |"
            )
    else:
        lines.append("| None observed | 0 | 0 | 0 | 0% | 0% | n/a |")

    skipped_jobs = sorted(
        ((key, agg) for key, agg in job_agg.items() if agg["skipped"]),
        key=lambda item: item[1]["skipped"],
        reverse=True,
    )[:15]
    lines.extend(["", "## Skipped and Pending Patterns", "", "| Job | Skipped | Observations |", "|---|---:|---|"])
    for key, agg in skipped_jobs:
        lines.append(f"| {key} | {agg['skipped']} | Mostly expected conditional gating or cancelled superseded runs. |")
    if in_progress:
        for run in in_progress[:8]:
            lines.append(f"| {run.get('workflowName')} run {run.get('databaseId')} | 0 | `{run.get('status')}` at collection time. |")
    if not skipped_jobs and not in_progress:
        lines.append("| None observed | 0 | No pending or skipped pattern surfaced in this sample. |")

    total_runner_minutes = sum(row["duration_minutes"] or 0 for row in job_rows if row["conclusion"] == "success")
    macos_minutes = sum(row["duration_minutes"] or 0 for row in job_rows if "macos" in row["name"].lower() or "macos" in row["runner"].lower())
    windows_minutes = sum(row["duration_minutes"] or 0 for row in job_rows if "windows" in row["name"].lower() or "windows" in row["runner"].lower())
    embedded_minutes = sum(row["duration_minutes"] or 0 for row in job_rows if "embedded" in row["name"].lower())
    lines.extend(
        [
            "",
            "## Cost and Noise Hot Spots",
            "",
            f"- Successful job runner time in sample: {fmt_minutes(total_runner_minutes)}.",
            f"- macOS successful job time: {fmt_minutes(macos_minutes)}. This is a premium hosted runner lane and should stay risk-gated.",
            f"- Windows successful job time: {fmt_minutes(windows_minutes)}. It is currently a smoke lane, which is appropriate.",
            f"- Embedded Dolt successful job time: {fmt_minutes(embedded_minutes)} across build/storage/cmd shard jobs. The shard fan-out is the dominant PR noise source when enabled.",
            "- Codecov uploads are steps inside the Linux test job rather than separate jobs in the public Jobs API. They are `continue-on-error`, so they add log/check noise and possible tail latency but usually should not block.",
            "",
            "## Tier Recommendations",
            "",
            "| Tier | Recommended contents | Why |",
            "|---|---|---|",
            "| Fast PR | build-tag policy, version consistency, no-beads check, doc flags, fmt, lint, Linux pure-Go short test, Windows smoke | Keeps default PR feedback focused on broad regressions and low queue/cost jobs. |",
            "| Risk PR | storage domain/uow, macOS race test, Cross-Version Smoke Tests, Regression Tests, Nix path workflow | Run when touched paths or labels indicate storage, packaging, release compatibility, Nix, or CLI behavior risk. |",
            "| Merge queue | Fast PR plus Linux short test, Windows smoke, regression detector, selected risk jobs for touched paths | Protects `main` without forcing every contributor edit through the full embedded matrix. |",
            "| Main push | Full CI as currently defined, docs deploy, regression, Nix when inputs changed | Main can absorb broader coverage after merge while preserving signal for regressions introduced by integration. |",
            "| Nightly | Nightly Full Tests, full embedded Dolt matrix, migration fidelity, longer cross-version count | Expensive and compatibility-heavy jobs belong here unless a PR explicitly changes the covered surface. |",
            "| Manual | Release, Test PyPI Publish, update flake/vendor hash workflows | Operator-triggered or bot-maintenance workflows should remain outside default PR critical path. |",
            "",
            "## Key Findings",
            "",
            f"- Recent successful PR CI P50/P95 wall-clock is {fmt_minutes(percentile(successful_ci_pr, 50))} / {fmt_minutes(percentile(successful_ci_pr, 95))}.",
            "- CI critical path is typically the longest Linux/macOS short test lane, storage/uow, or embedded cmd shard when the embedded tier is enabled.",
            "- Regression Tests are quick when skipped by detector, but become a meaningful PR lane when path risk or labels enable the differential suite.",
            "- Cross-Version Smoke Tests are parallel version shards; they are bounded, but they create check noise on routine PRs.",
            "- The embedded Dolt build plus 20 cmd shards has high aggregate runner-minute cost and should remain risk-gated, main/nightly, or manually requested.",
        ]
    )
    return "\n".join(lines) + "\n"


def markdown_tables_to_html(markdown: str) -> str:
    body: list[str] = []
    in_list = False
    lines = markdown.splitlines()
    i = 0
    while i < len(lines):
        line = lines[i]
        if line.startswith("# "):
            if in_list:
                body.append("</ul>")
                in_list = False
            body.append(f"<h1>{html.escape(line[2:])}</h1>")
        elif line.startswith("## "):
            if in_list:
                body.append("</ul>")
                in_list = False
            body.append(f"<h2>{html.escape(line[3:])}</h2>")
        elif line.startswith("- "):
            if not in_list:
                body.append("<ul>")
                in_list = True
            body.append(f"<li>{html.escape(line[2:])}</li>")
        elif line.startswith("|") and i + 1 < len(lines) and lines[i + 1].startswith("|---"):
            if in_list:
                body.append("</ul>")
                in_list = False
            headers = [cell.strip() for cell in line.strip("|").split("|")]
            body.append("<table><thead><tr>" + "".join(f"<th>{html.escape(h)}</th>" for h in headers) + "</tr></thead><tbody>")
            i += 2
            while i < len(lines) and lines[i].startswith("|"):
                cells = [cell.strip() for cell in lines[i].strip("|").split("|")]
                body.append("<tr>" + "".join(f"<td>{html.escape(c)}</td>" for c in cells) + "</tr>")
                i += 1
            body.append("</tbody></table>")
            continue
        elif line.strip():
            if in_list:
                body.append("</ul>")
                in_list = False
            body.append(f"<p>{html.escape(line)}</p>")
        i += 1
    if in_list:
        body.append("</ul>")
    return "\n".join(body)


def render_html(markdown: str) -> str:
    body = markdown_tables_to_html(markdown)
    return f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>CI Timing Report</title>
<style>
:root {{
  color-scheme: light dark;
  --bg: #f7f8fa;
  --fg: #20242a;
  --muted: #5d6673;
  --line: #d8dde6;
  --panel: #ffffff;
  --accent: #0b6bcb;
}}
@media (prefers-color-scheme: dark) {{
  :root {{
    --bg: #111418;
    --fg: #eceff4;
    --muted: #aab3c2;
    --line: #2e3642;
    --panel: #181d24;
    --accent: #78b7ff;
  }}
}}
body {{
  margin: 0;
  background: var(--bg);
  color: var(--fg);
  font: 15px/1.5 system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
}}
main {{
  max-width: 1180px;
  margin: 0 auto;
  padding: 32px 20px 56px;
}}
h1, h2 {{
  line-height: 1.2;
}}
h1 {{
  font-size: 2rem;
  margin: 0 0 1rem;
}}
h2 {{
  border-top: 1px solid var(--line);
  margin-top: 2rem;
  padding-top: 1.25rem;
}}
p, li {{
  color: var(--muted);
}}
table {{
  width: 100%;
  border-collapse: collapse;
  margin: 1rem 0 1.5rem;
  background: var(--panel);
  border: 1px solid var(--line);
}}
th, td {{
  padding: 0.55rem 0.7rem;
  border-bottom: 1px solid var(--line);
  text-align: left;
  vertical-align: top;
}}
th {{
  color: var(--fg);
  background: color-mix(in srgb, var(--accent) 10%, transparent);
  font-weight: 650;
}}
code {{
  font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace;
  font-size: 0.92em;
}}
</style>
</head>
<body>
<main>
{body}
</main>
</body>
</html>
"""


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--repo", default="gastownhall/beads")
    parser.add_argument("--runs", type=int, default=120)
    parser.add_argument("--out-dir", type=Path, default=Path("docs/reports"))
    parser.add_argument("--workers", type=int, default=8)
    args = parser.parse_args()

    root = Path.cwd()
    workflows = workflow_file_summary(root)
    runs = collect_runs(args.repo, args.runs)
    selected = [run for run in runs if run.get("status") == "completed"]

    jobs_by_run: dict[int, list[dict[str, Any]]] = {}
    with concurrent.futures.ThreadPoolExecutor(max_workers=args.workers) as executor:
        future_to_run = {executor.submit(collect_jobs, args.repo, run["databaseId"]): run for run in selected}
        for future in concurrent.futures.as_completed(future_to_run):
            run = future_to_run[future]
            jobs_by_run[run["databaseId"]] = future.result()

    summary = summarize(runs, jobs_by_run)
    markdown = render_markdown(args.repo, args.runs, summary, workflows)
    html_report = render_html(markdown)

    args.out_dir.mkdir(parents=True, exist_ok=True)
    md_path = args.out_dir / "ci-timing-report.md"
    html_path = args.out_dir / "ci-timing-report.html"
    md_path.write_text(markdown, encoding="utf-8")
    html_path.write_text(html_report, encoding="utf-8")
    print(f"wrote {md_path}")
    print(f"wrote {html_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
