ALTER TABLE events MODIFY old_value LONGTEXT;
ALTER TABLE events MODIFY new_value LONGTEXT;
ALTER TABLE wisp_events MODIFY old_value LONGTEXT DEFAULT '';
ALTER TABLE wisp_events MODIFY new_value LONGTEXT DEFAULT '';
